/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using FalaAI.Api.Client;
using FalaAI.Api.Model;

namespace FalaAI.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAnalysisApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Compliance Risk Audit â€” conversation compliance analysis
        /// </summary>
        /// <remarks>
        /// Analyzes a call transcript for compliance risks. Returns a score (0-100), classification level, violations, positives, and a detailed HTML report.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/auditoriaRisco&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;duration_seconds&#39;: 151.0,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;response_language&#39;: &#39;en-US&#39;     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/auditoriaRisco \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;duration_seconds\&quot;: 151.0,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;response_language\&quot;: \&quot;en-US\&quot;   }&#39; &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditoriaRiscoRequest"></param>
        /// <returns>AuditoriaRiscoV2Response</returns>
        AuditoriaRiscoV2Response CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPost(AuditoriaRiscoRequest auditoriaRiscoRequest);

        /// <summary>
        /// Compliance Risk Audit â€” conversation compliance analysis
        /// </summary>
        /// <remarks>
        /// Analyzes a call transcript for compliance risks. Returns a score (0-100), classification level, violations, positives, and a detailed HTML report.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/auditoriaRisco&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;duration_seconds&#39;: 151.0,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;response_language&#39;: &#39;en-US&#39;     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/auditoriaRisco \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;duration_seconds\&quot;: 151.0,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;response_language\&quot;: \&quot;en-US\&quot;   }&#39; &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditoriaRiscoRequest"></param>
        /// <returns>ApiResponse of AuditoriaRiscoV2Response</returns>
        ApiResponse<AuditoriaRiscoV2Response> CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPostWithHttpInfo(AuditoriaRiscoRequest auditoriaRiscoRequest);
        /// <summary>
        /// Analyze a call transcript â€” 5 parallel analyses
        /// </summary>
        /// <remarks>
        /// Runs 5 independent analyses on a call transcript: dialogue summary, contact reason, identified action, label classification, and sentiment.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/diagnostic&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;duration_seconds&#39;: 151.0     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/diagnostic \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;duration_seconds\&quot;: 151.0   }&#39; &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="diagnosticRequest"></param>
        /// <returns>DiagnosticResponse</returns>
        DiagnosticResponse CreateDiagnosticV1AnalyzeDiagnosticPost(DiagnosticRequest diagnosticRequest);

        /// <summary>
        /// Analyze a call transcript â€” 5 parallel analyses
        /// </summary>
        /// <remarks>
        /// Runs 5 independent analyses on a call transcript: dialogue summary, contact reason, identified action, label classification, and sentiment.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/diagnostic&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;duration_seconds&#39;: 151.0     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/diagnostic \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;duration_seconds\&quot;: 151.0   }&#39; &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="diagnosticRequest"></param>
        /// <returns>ApiResponse of DiagnosticResponse</returns>
        ApiResponse<DiagnosticResponse> CreateDiagnosticV1AnalyzeDiagnosticPostWithHttpInfo(DiagnosticRequest diagnosticRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAnalysisApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Compliance Risk Audit â€” conversation compliance analysis
        /// </summary>
        /// <remarks>
        /// Analyzes a call transcript for compliance risks. Returns a score (0-100), classification level, violations, positives, and a detailed HTML report.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/auditoriaRisco&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;duration_seconds&#39;: 151.0,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;response_language&#39;: &#39;en-US&#39;     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/auditoriaRisco \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;duration_seconds\&quot;: 151.0,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;response_language\&quot;: \&quot;en-US\&quot;   }&#39; &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditoriaRiscoRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuditoriaRiscoV2Response</returns>
        System.Threading.Tasks.Task<AuditoriaRiscoV2Response> CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPostAsync(AuditoriaRiscoRequest auditoriaRiscoRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Compliance Risk Audit â€” conversation compliance analysis
        /// </summary>
        /// <remarks>
        /// Analyzes a call transcript for compliance risks. Returns a score (0-100), classification level, violations, positives, and a detailed HTML report.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/auditoriaRisco&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;duration_seconds&#39;: 151.0,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;response_language&#39;: &#39;en-US&#39;     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/auditoriaRisco \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;duration_seconds\&quot;: 151.0,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;response_language\&quot;: \&quot;en-US\&quot;   }&#39; &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditoriaRiscoRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuditoriaRiscoV2Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<AuditoriaRiscoV2Response>> CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPostWithHttpInfoAsync(AuditoriaRiscoRequest auditoriaRiscoRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Analyze a call transcript â€” 5 parallel analyses
        /// </summary>
        /// <remarks>
        /// Runs 5 independent analyses on a call transcript: dialogue summary, contact reason, identified action, label classification, and sentiment.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/diagnostic&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;duration_seconds&#39;: 151.0     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/diagnostic \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;duration_seconds\&quot;: 151.0   }&#39; &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="diagnosticRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DiagnosticResponse</returns>
        System.Threading.Tasks.Task<DiagnosticResponse> CreateDiagnosticV1AnalyzeDiagnosticPostAsync(DiagnosticRequest diagnosticRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Analyze a call transcript â€” 5 parallel analyses
        /// </summary>
        /// <remarks>
        /// Runs 5 independent analyses on a call transcript: dialogue summary, contact reason, identified action, label classification, and sentiment.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/diagnostic&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;duration_seconds&#39;: 151.0     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/diagnostic \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;duration_seconds\&quot;: 151.0   }&#39; &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="diagnosticRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DiagnosticResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DiagnosticResponse>> CreateDiagnosticV1AnalyzeDiagnosticPostWithHttpInfoAsync(DiagnosticRequest diagnosticRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAnalysisApi : IAnalysisApiSync, IAnalysisApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AnalysisApi : IDisposable, IAnalysisApi
    {
        private FalaAI.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AnalysisApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public AnalysisApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AnalysisApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public AnalysisApi(string basePath)
        {
            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                new FalaAI.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AnalysisApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public AnalysisApi(FalaAI.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AnalysisApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AnalysisApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AnalysisApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AnalysisApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                new FalaAI.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AnalysisApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AnalysisApi(HttpClient client, FalaAI.Api.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AnalysisApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public AnalysisApi(FalaAI.Api.Client.ISynchronousClient client, FalaAI.Api.Client.IAsynchronousClient asyncClient, FalaAI.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public FalaAI.Api.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public FalaAI.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public FalaAI.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public FalaAI.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public FalaAI.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Compliance Risk Audit â€” conversation compliance analysis Analyzes a call transcript for compliance risks. Returns a score (0-100), classification level, violations, positives, and a detailed HTML report.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/auditoriaRisco&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;duration_seconds&#39;: 151.0,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;response_language&#39;: &#39;en-US&#39;     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/auditoriaRisco \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;duration_seconds\&quot;: 151.0,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;response_language\&quot;: \&quot;en-US\&quot;   }&#39; &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditoriaRiscoRequest"></param>
        /// <returns>AuditoriaRiscoV2Response</returns>
        public AuditoriaRiscoV2Response CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPost(AuditoriaRiscoRequest auditoriaRiscoRequest)
        {
            FalaAI.Api.Client.ApiResponse<AuditoriaRiscoV2Response> localVarResponse = CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPostWithHttpInfo(auditoriaRiscoRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Compliance Risk Audit â€” conversation compliance analysis Analyzes a call transcript for compliance risks. Returns a score (0-100), classification level, violations, positives, and a detailed HTML report.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/auditoriaRisco&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;duration_seconds&#39;: 151.0,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;response_language&#39;: &#39;en-US&#39;     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/auditoriaRisco \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;duration_seconds\&quot;: 151.0,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;response_language\&quot;: \&quot;en-US\&quot;   }&#39; &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditoriaRiscoRequest"></param>
        /// <returns>ApiResponse of AuditoriaRiscoV2Response</returns>
        public FalaAI.Api.Client.ApiResponse<AuditoriaRiscoV2Response> CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPostWithHttpInfo(AuditoriaRiscoRequest auditoriaRiscoRequest)
        {
            // verify the required parameter 'auditoriaRiscoRequest' is set
            if (auditoriaRiscoRequest == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'auditoriaRiscoRequest' when calling AnalysisApi->CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPost");

            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = auditoriaRiscoRequest;

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<AuditoriaRiscoV2Response>("/v1/analyze/auditoriaRisco", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Compliance Risk Audit â€” conversation compliance analysis Analyzes a call transcript for compliance risks. Returns a score (0-100), classification level, violations, positives, and a detailed HTML report.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/auditoriaRisco&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;duration_seconds&#39;: 151.0,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;response_language&#39;: &#39;en-US&#39;     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/auditoriaRisco \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;duration_seconds\&quot;: 151.0,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;response_language\&quot;: \&quot;en-US\&quot;   }&#39; &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditoriaRiscoRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuditoriaRiscoV2Response</returns>
        public async System.Threading.Tasks.Task<AuditoriaRiscoV2Response> CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPostAsync(AuditoriaRiscoRequest auditoriaRiscoRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            FalaAI.Api.Client.ApiResponse<AuditoriaRiscoV2Response> localVarResponse = await CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPostWithHttpInfoAsync(auditoriaRiscoRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Compliance Risk Audit â€” conversation compliance analysis Analyzes a call transcript for compliance risks. Returns a score (0-100), classification level, violations, positives, and a detailed HTML report.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/auditoriaRisco&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;duration_seconds&#39;: 151.0,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;response_language&#39;: &#39;en-US&#39;     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/auditoriaRisco \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;duration_seconds\&quot;: 151.0,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;response_language\&quot;: \&quot;en-US\&quot;   }&#39; &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditoriaRiscoRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuditoriaRiscoV2Response)</returns>
        public async System.Threading.Tasks.Task<FalaAI.Api.Client.ApiResponse<AuditoriaRiscoV2Response>> CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPostWithHttpInfoAsync(AuditoriaRiscoRequest auditoriaRiscoRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'auditoriaRiscoRequest' is set
            if (auditoriaRiscoRequest == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'auditoriaRiscoRequest' when calling AnalysisApi->CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPost");


            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = auditoriaRiscoRequest;

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<AuditoriaRiscoV2Response>("/v1/analyze/auditoriaRisco", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAuditoriaRiscoV1AnalyzeAuditoriaRiscoPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Analyze a call transcript â€” 5 parallel analyses Runs 5 independent analyses on a call transcript: dialogue summary, contact reason, identified action, label classification, and sentiment.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/diagnostic&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;duration_seconds&#39;: 151.0     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/diagnostic \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;duration_seconds\&quot;: 151.0   }&#39; &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="diagnosticRequest"></param>
        /// <returns>DiagnosticResponse</returns>
        public DiagnosticResponse CreateDiagnosticV1AnalyzeDiagnosticPost(DiagnosticRequest diagnosticRequest)
        {
            FalaAI.Api.Client.ApiResponse<DiagnosticResponse> localVarResponse = CreateDiagnosticV1AnalyzeDiagnosticPostWithHttpInfo(diagnosticRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Analyze a call transcript â€” 5 parallel analyses Runs 5 independent analyses on a call transcript: dialogue summary, contact reason, identified action, label classification, and sentiment.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/diagnostic&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;duration_seconds&#39;: 151.0     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/diagnostic \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;duration_seconds\&quot;: 151.0   }&#39; &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="diagnosticRequest"></param>
        /// <returns>ApiResponse of DiagnosticResponse</returns>
        public FalaAI.Api.Client.ApiResponse<DiagnosticResponse> CreateDiagnosticV1AnalyzeDiagnosticPostWithHttpInfo(DiagnosticRequest diagnosticRequest)
        {
            // verify the required parameter 'diagnosticRequest' is set
            if (diagnosticRequest == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'diagnosticRequest' when calling AnalysisApi->CreateDiagnosticV1AnalyzeDiagnosticPost");

            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = diagnosticRequest;

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DiagnosticResponse>("/v1/analyze/diagnostic", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDiagnosticV1AnalyzeDiagnosticPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Analyze a call transcript â€” 5 parallel analyses Runs 5 independent analyses on a call transcript: dialogue summary, contact reason, identified action, label classification, and sentiment.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/diagnostic&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;duration_seconds&#39;: 151.0     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/diagnostic \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;duration_seconds\&quot;: 151.0   }&#39; &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="diagnosticRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DiagnosticResponse</returns>
        public async System.Threading.Tasks.Task<DiagnosticResponse> CreateDiagnosticV1AnalyzeDiagnosticPostAsync(DiagnosticRequest diagnosticRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            FalaAI.Api.Client.ApiResponse<DiagnosticResponse> localVarResponse = await CreateDiagnosticV1AnalyzeDiagnosticPostWithHttpInfoAsync(diagnosticRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Analyze a call transcript â€” 5 parallel analyses Runs 5 independent analyses on a call transcript: dialogue summary, contact reason, identified action, label classification, and sentiment.  **Python:** &#x60;&#x60;&#x60;python import httpx  response &#x3D; httpx.post(     &#39;https://api.fala.ai/v1/analyze/diagnostic&#39;,     headers&#x3D;{&#39;Authorization&#39;: &#39;Bearer fai_xxx&#39;},     json&#x3D;{         &#39;dialog&#39;: &#39;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.&#39;,         &#39;language&#39;: &#39;pt-BR&#39;,         &#39;duration_seconds&#39;: 151.0     } ) print(response.json()) &#x60;&#x60;&#x60;  **cURL:** &#x60;&#x60;&#x60;bash curl https://api.fala.ai/v1/analyze/diagnostic \\   -H &#39;Authorization: Bearer fai_xxx&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -d &#39;{     \&quot;dialog\&quot;: \&quot;Speaker 1: [00:00:00.540 - 00:00:01.139] Hi, Alex.\&quot;,     \&quot;language\&quot;: \&quot;pt-BR\&quot;,     \&quot;duration_seconds\&quot;: 151.0   }&#39; &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="diagnosticRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DiagnosticResponse)</returns>
        public async System.Threading.Tasks.Task<FalaAI.Api.Client.ApiResponse<DiagnosticResponse>> CreateDiagnosticV1AnalyzeDiagnosticPostWithHttpInfoAsync(DiagnosticRequest diagnosticRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'diagnosticRequest' is set
            if (diagnosticRequest == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'diagnosticRequest' when calling AnalysisApi->CreateDiagnosticV1AnalyzeDiagnosticPost");


            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = diagnosticRequest;

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<DiagnosticResponse>("/v1/analyze/diagnostic", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDiagnosticV1AnalyzeDiagnosticPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
