/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using FalaAI.Api.Client;
using FalaAI.Api.Model;

namespace FalaAI.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISpeechApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Transcribe audio to text
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="model"> (optional, default to &quot;falaai-transcribe-1&quot;)</param>
        /// <param name="language"> (optional, default to &quot;pt&quot;)</param>
        /// <param name="clientReferenceId">Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)</param>
        /// <returns>TranscriptionResponse</returns>
        TranscriptionResponse CreateTranscriptionV1AudioTranscriptionsPost(FileParameter file, string? model = default, string? language = default, string? clientReferenceId = default);

        /// <summary>
        /// Transcribe audio to text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="model"> (optional, default to &quot;falaai-transcribe-1&quot;)</param>
        /// <param name="language"> (optional, default to &quot;pt&quot;)</param>
        /// <param name="clientReferenceId">Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)</param>
        /// <returns>ApiResponse of TranscriptionResponse</returns>
        ApiResponse<TranscriptionResponse> CreateTranscriptionV1AudioTranscriptionsPostWithHttpInfo(FileParameter file, string? model = default, string? language = default, string? clientReferenceId = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISpeechApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Transcribe audio to text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="model"> (optional, default to &quot;falaai-transcribe-1&quot;)</param>
        /// <param name="language"> (optional, default to &quot;pt&quot;)</param>
        /// <param name="clientReferenceId">Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TranscriptionResponse</returns>
        System.Threading.Tasks.Task<TranscriptionResponse> CreateTranscriptionV1AudioTranscriptionsPostAsync(FileParameter file, string? model = default, string? language = default, string? clientReferenceId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Transcribe audio to text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="model"> (optional, default to &quot;falaai-transcribe-1&quot;)</param>
        /// <param name="language"> (optional, default to &quot;pt&quot;)</param>
        /// <param name="clientReferenceId">Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TranscriptionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TranscriptionResponse>> CreateTranscriptionV1AudioTranscriptionsPostWithHttpInfoAsync(FileParameter file, string? model = default, string? language = default, string? clientReferenceId = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISpeechApi : ISpeechApiSync, ISpeechApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SpeechApi : IDisposable, ISpeechApi
    {
        private FalaAI.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SpeechApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public SpeechApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpeechApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public SpeechApi(string basePath)
        {
            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                new FalaAI.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpeechApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public SpeechApi(FalaAI.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpeechApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SpeechApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpeechApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SpeechApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                new FalaAI.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpeechApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SpeechApi(HttpClient client, FalaAI.Api.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpeechApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public SpeechApi(FalaAI.Api.Client.ISynchronousClient client, FalaAI.Api.Client.IAsynchronousClient asyncClient, FalaAI.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public FalaAI.Api.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public FalaAI.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public FalaAI.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public FalaAI.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public FalaAI.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Transcribe audio to text 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="model"> (optional, default to &quot;falaai-transcribe-1&quot;)</param>
        /// <param name="language"> (optional, default to &quot;pt&quot;)</param>
        /// <param name="clientReferenceId">Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)</param>
        /// <returns>TranscriptionResponse</returns>
        public TranscriptionResponse CreateTranscriptionV1AudioTranscriptionsPost(FileParameter file, string? model = default, string? language = default, string? clientReferenceId = default)
        {
            FalaAI.Api.Client.ApiResponse<TranscriptionResponse> localVarResponse = CreateTranscriptionV1AudioTranscriptionsPostWithHttpInfo(file, model, language, clientReferenceId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Transcribe audio to text 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="model"> (optional, default to &quot;falaai-transcribe-1&quot;)</param>
        /// <param name="language"> (optional, default to &quot;pt&quot;)</param>
        /// <param name="clientReferenceId">Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)</param>
        /// <returns>ApiResponse of TranscriptionResponse</returns>
        public FalaAI.Api.Client.ApiResponse<TranscriptionResponse> CreateTranscriptionV1AudioTranscriptionsPostWithHttpInfo(FileParameter file, string? model = default, string? language = default, string? clientReferenceId = default)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'file' when calling SpeechApi->CreateTranscriptionV1AudioTranscriptionsPost");

            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FileParameters.Add("file", file);
            if (model != null)
            {
                localVarRequestOptions.FormParameters.Add("model", FalaAI.Api.Client.ClientUtils.ParameterToString(model)); // form parameter
            }
            if (language != null)
            {
                localVarRequestOptions.FormParameters.Add("language", FalaAI.Api.Client.ClientUtils.ParameterToString(language)); // form parameter
            }
            if (clientReferenceId != null)
            {
                localVarRequestOptions.FormParameters.Add("client_reference_id", FalaAI.Api.Client.ClientUtils.ParameterToString(clientReferenceId)); // form parameter
            }

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<TranscriptionResponse>("/v1/audio/transcriptions", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateTranscriptionV1AudioTranscriptionsPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Transcribe audio to text 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="model"> (optional, default to &quot;falaai-transcribe-1&quot;)</param>
        /// <param name="language"> (optional, default to &quot;pt&quot;)</param>
        /// <param name="clientReferenceId">Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TranscriptionResponse</returns>
        public async System.Threading.Tasks.Task<TranscriptionResponse> CreateTranscriptionV1AudioTranscriptionsPostAsync(FileParameter file, string? model = default, string? language = default, string? clientReferenceId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            FalaAI.Api.Client.ApiResponse<TranscriptionResponse> localVarResponse = await CreateTranscriptionV1AudioTranscriptionsPostWithHttpInfoAsync(file, model, language, clientReferenceId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Transcribe audio to text 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="model"> (optional, default to &quot;falaai-transcribe-1&quot;)</param>
        /// <param name="language"> (optional, default to &quot;pt&quot;)</param>
        /// <param name="clientReferenceId">Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-]. Not idempotency. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TranscriptionResponse)</returns>
        public async System.Threading.Tasks.Task<FalaAI.Api.Client.ApiResponse<TranscriptionResponse>> CreateTranscriptionV1AudioTranscriptionsPostWithHttpInfoAsync(FileParameter file, string? model = default, string? language = default, string? clientReferenceId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'file' when calling SpeechApi->CreateTranscriptionV1AudioTranscriptionsPost");


            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FileParameters.Add("file", file);
            if (model != null)
            {
                localVarRequestOptions.FormParameters.Add("model", FalaAI.Api.Client.ClientUtils.ParameterToString(model)); // form parameter
            }
            if (language != null)
            {
                localVarRequestOptions.FormParameters.Add("language", FalaAI.Api.Client.ClientUtils.ParameterToString(language)); // form parameter
            }
            if (clientReferenceId != null)
            {
                localVarRequestOptions.FormParameters.Add("client_reference_id", FalaAI.Api.Client.ClientUtils.ParameterToString(clientReferenceId)); // form parameter
            }

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<TranscriptionResponse>("/v1/audio/transcriptions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateTranscriptionV1AudioTranscriptionsPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
