/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using FalaAI.Api.Client;
using FalaAI.Api.Model;

namespace FalaAI.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsageApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Usage By Key
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"> (optional)</param>
        /// <returns>List&lt;UsageByKeyItem&gt;</returns>
        List<UsageByKeyItem> GetUsageByKeyV1UsageByKeyGet(string? keyId = default);

        /// <summary>
        /// Get Usage By Key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"> (optional)</param>
        /// <returns>ApiResponse of List&lt;UsageByKeyItem&gt;</returns>
        ApiResponse<List<UsageByKeyItem>> GetUsageByKeyV1UsageByKeyGetWithHttpInfo(string? keyId = default);
        /// <summary>
        /// Get Usage Log
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="apiKeyId"> (optional)</param>
        /// <returns>UsageLogResponse</returns>
        UsageLogResponse GetUsageLogV1UsageLogGet(int? page = default, int? limit = default, string? apiKeyId = default);

        /// <summary>
        /// Get Usage Log
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="apiKeyId"> (optional)</param>
        /// <returns>ApiResponse of UsageLogResponse</returns>
        ApiResponse<UsageLogResponse> GetUsageLogV1UsageLogGetWithHttpInfo(int? page = default, int? limit = default, string? apiKeyId = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsageApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Usage By Key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;UsageByKeyItem&gt;</returns>
        System.Threading.Tasks.Task<List<UsageByKeyItem>> GetUsageByKeyV1UsageByKeyGetAsync(string? keyId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Usage By Key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;UsageByKeyItem&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<UsageByKeyItem>>> GetUsageByKeyV1UsageByKeyGetWithHttpInfoAsync(string? keyId = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Usage Log
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="apiKeyId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UsageLogResponse</returns>
        System.Threading.Tasks.Task<UsageLogResponse> GetUsageLogV1UsageLogGetAsync(int? page = default, int? limit = default, string? apiKeyId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Usage Log
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="apiKeyId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UsageLogResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<UsageLogResponse>> GetUsageLogV1UsageLogGetWithHttpInfoAsync(int? page = default, int? limit = default, string? apiKeyId = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsageApi : IUsageApiSync, IUsageApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UsageApi : IDisposable, IUsageApi
    {
        private FalaAI.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UsageApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public UsageApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsageApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public UsageApi(string basePath)
        {
            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                new FalaAI.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsageApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public UsageApi(FalaAI.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsageApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public UsageApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsageApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public UsageApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                new FalaAI.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsageApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public UsageApi(HttpClient client, FalaAI.Api.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsageApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public UsageApi(FalaAI.Api.Client.ISynchronousClient client, FalaAI.Api.Client.IAsynchronousClient asyncClient, FalaAI.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public FalaAI.Api.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public FalaAI.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public FalaAI.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public FalaAI.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public FalaAI.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Usage By Key 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"> (optional)</param>
        /// <returns>List&lt;UsageByKeyItem&gt;</returns>
        public List<UsageByKeyItem> GetUsageByKeyV1UsageByKeyGet(string? keyId = default)
        {
            FalaAI.Api.Client.ApiResponse<List<UsageByKeyItem>> localVarResponse = GetUsageByKeyV1UsageByKeyGetWithHttpInfo(keyId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Usage By Key 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"> (optional)</param>
        /// <returns>ApiResponse of List&lt;UsageByKeyItem&gt;</returns>
        public FalaAI.Api.Client.ApiResponse<List<UsageByKeyItem>> GetUsageByKeyV1UsageByKeyGetWithHttpInfo(string? keyId = default)
        {
            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (keyId != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "key_id", keyId));
            }

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<UsageByKeyItem>>("/v1/usage/by-key", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUsageByKeyV1UsageByKeyGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Usage By Key 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;UsageByKeyItem&gt;</returns>
        public async System.Threading.Tasks.Task<List<UsageByKeyItem>> GetUsageByKeyV1UsageByKeyGetAsync(string? keyId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            FalaAI.Api.Client.ApiResponse<List<UsageByKeyItem>> localVarResponse = await GetUsageByKeyV1UsageByKeyGetWithHttpInfoAsync(keyId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Usage By Key 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keyId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;UsageByKeyItem&gt;)</returns>
        public async System.Threading.Tasks.Task<FalaAI.Api.Client.ApiResponse<List<UsageByKeyItem>>> GetUsageByKeyV1UsageByKeyGetWithHttpInfoAsync(string? keyId = default, System.Threading.CancellationToken cancellationToken = default)
        {

            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (keyId != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "key_id", keyId));
            }

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<UsageByKeyItem>>("/v1/usage/by-key", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUsageByKeyV1UsageByKeyGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Usage Log 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="apiKeyId"> (optional)</param>
        /// <returns>UsageLogResponse</returns>
        public UsageLogResponse GetUsageLogV1UsageLogGet(int? page = default, int? limit = default, string? apiKeyId = default)
        {
            FalaAI.Api.Client.ApiResponse<UsageLogResponse> localVarResponse = GetUsageLogV1UsageLogGetWithHttpInfo(page, limit, apiKeyId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Usage Log 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="apiKeyId"> (optional)</param>
        /// <returns>ApiResponse of UsageLogResponse</returns>
        public FalaAI.Api.Client.ApiResponse<UsageLogResponse> GetUsageLogV1UsageLogGetWithHttpInfo(int? page = default, int? limit = default, string? apiKeyId = default)
        {
            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (apiKeyId != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "api_key_id", apiKeyId));
            }

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<UsageLogResponse>("/v1/usage/log", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUsageLogV1UsageLogGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Usage Log 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="apiKeyId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UsageLogResponse</returns>
        public async System.Threading.Tasks.Task<UsageLogResponse> GetUsageLogV1UsageLogGetAsync(int? page = default, int? limit = default, string? apiKeyId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            FalaAI.Api.Client.ApiResponse<UsageLogResponse> localVarResponse = await GetUsageLogV1UsageLogGetWithHttpInfoAsync(page, limit, apiKeyId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Usage Log 
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="apiKeyId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UsageLogResponse)</returns>
        public async System.Threading.Tasks.Task<FalaAI.Api.Client.ApiResponse<UsageLogResponse>> GetUsageLogV1UsageLogGetWithHttpInfoAsync(int? page = default, int? limit = default, string? apiKeyId = default, System.Threading.CancellationToken cancellationToken = default)
        {

            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (apiKeyId != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "api_key_id", apiKeyId));
            }

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<UsageLogResponse>("/v1/usage/log", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUsageLogV1UsageLogGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
