/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using FalaAI.Api.Client;
using FalaAI.Api.Model;

namespace FalaAI.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Criar webhook de alertas
        /// </summary>
        /// <remarks>
        /// Cria inscricao para eventos de alerta (10 alertas). Payload enviado: WebhookPayload(event, data, timestamp) com HMAC FalaAI-Signature. Para comprovar a origem, recalcule HMAC-SHA256 de \&quot;timestamp.body\&quot; com seu secret (exemplos: /examples/download/python.zip e nodejs.zip, arquivo webhook_verify).
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createWebhookRequest"></param>
        /// <returns>WebhookItem</returns>
        WebhookItem CreateWebhookV1WebhooksPost(CreateWebhookRequest createWebhookRequest);

        /// <summary>
        /// Criar webhook de alertas
        /// </summary>
        /// <remarks>
        /// Cria inscricao para eventos de alerta (10 alertas). Payload enviado: WebhookPayload(event, data, timestamp) com HMAC FalaAI-Signature. Para comprovar a origem, recalcule HMAC-SHA256 de \&quot;timestamp.body\&quot; com seu secret (exemplos: /examples/download/python.zip e nodejs.zip, arquivo webhook_verify).
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createWebhookRequest"></param>
        /// <returns>ApiResponse of WebhookItem</returns>
        ApiResponse<WebhookItem> CreateWebhookV1WebhooksPostWithHttpInfo(CreateWebhookRequest createWebhookRequest);
        /// <summary>
        /// Remover webhook
        /// </summary>
        /// <remarks>
        /// Remove inscricao de webhook por ID.
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <returns>MessageResponse</returns>
        MessageResponse DeleteWebhookV1WebhooksWebhookIdDelete(string webhookId);

        /// <summary>
        /// Remover webhook
        /// </summary>
        /// <remarks>
        /// Remove inscricao de webhook por ID.
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <returns>ApiResponse of MessageResponse</returns>
        ApiResponse<MessageResponse> DeleteWebhookV1WebhooksWebhookIdDeleteWithHttpInfo(string webhookId);
        /// <summary>
        /// Listar webhooks de alertas
        /// </summary>
        /// <remarks>
        /// Lista webhooks do usuario autenticado (10 alertas). Paginado. Inclui o secret da assinatura da URL (sempre visivel ao dono).
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Pagina (1-indexed) (optional, default to 1)</param>
        /// <param name="limit">Itens por pagina (max 100) (optional, default to 20)</param>
        /// <returns>WebhookListResponse</returns>
        WebhookListResponse ListWebhooksV1WebhooksGet(int? page = default, int? limit = default);

        /// <summary>
        /// Listar webhooks de alertas
        /// </summary>
        /// <remarks>
        /// Lista webhooks do usuario autenticado (10 alertas). Paginado. Inclui o secret da assinatura da URL (sempre visivel ao dono).
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Pagina (1-indexed) (optional, default to 1)</param>
        /// <param name="limit">Itens por pagina (max 100) (optional, default to 20)</param>
        /// <returns>ApiResponse of WebhookListResponse</returns>
        ApiResponse<WebhookListResponse> ListWebhooksV1WebhooksGetWithHttpInfo(int? page = default, int? limit = default);
        /// <summary>
        /// Atualizar webhook
        /// </summary>
        /// <remarks>
        /// Atualiza name/url/events/retry_enabled/active do webhook. Eventos validos: 10 alertas.
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="updateWebhookRequest"></param>
        /// <returns>MessageResponse</returns>
        MessageResponse UpdateWebhookV1WebhooksWebhookIdPut(string webhookId, UpdateWebhookRequest updateWebhookRequest);

        /// <summary>
        /// Atualizar webhook
        /// </summary>
        /// <remarks>
        /// Atualiza name/url/events/retry_enabled/active do webhook. Eventos validos: 10 alertas.
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="updateWebhookRequest"></param>
        /// <returns>ApiResponse of MessageResponse</returns>
        ApiResponse<MessageResponse> UpdateWebhookV1WebhooksWebhookIdPutWithHttpInfo(string webhookId, UpdateWebhookRequest updateWebhookRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Criar webhook de alertas
        /// </summary>
        /// <remarks>
        /// Cria inscricao para eventos de alerta (10 alertas). Payload enviado: WebhookPayload(event, data, timestamp) com HMAC FalaAI-Signature. Para comprovar a origem, recalcule HMAC-SHA256 de \&quot;timestamp.body\&quot; com seu secret (exemplos: /examples/download/python.zip e nodejs.zip, arquivo webhook_verify).
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WebhookItem</returns>
        System.Threading.Tasks.Task<WebhookItem> CreateWebhookV1WebhooksPostAsync(CreateWebhookRequest createWebhookRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Criar webhook de alertas
        /// </summary>
        /// <remarks>
        /// Cria inscricao para eventos de alerta (10 alertas). Payload enviado: WebhookPayload(event, data, timestamp) com HMAC FalaAI-Signature. Para comprovar a origem, recalcule HMAC-SHA256 de \&quot;timestamp.body\&quot; com seu secret (exemplos: /examples/download/python.zip e nodejs.zip, arquivo webhook_verify).
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WebhookItem)</returns>
        System.Threading.Tasks.Task<ApiResponse<WebhookItem>> CreateWebhookV1WebhooksPostWithHttpInfoAsync(CreateWebhookRequest createWebhookRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Remover webhook
        /// </summary>
        /// <remarks>
        /// Remove inscricao de webhook por ID.
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MessageResponse</returns>
        System.Threading.Tasks.Task<MessageResponse> DeleteWebhookV1WebhooksWebhookIdDeleteAsync(string webhookId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Remover webhook
        /// </summary>
        /// <remarks>
        /// Remove inscricao de webhook por ID.
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MessageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MessageResponse>> DeleteWebhookV1WebhooksWebhookIdDeleteWithHttpInfoAsync(string webhookId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Listar webhooks de alertas
        /// </summary>
        /// <remarks>
        /// Lista webhooks do usuario autenticado (10 alertas). Paginado. Inclui o secret da assinatura da URL (sempre visivel ao dono).
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Pagina (1-indexed) (optional, default to 1)</param>
        /// <param name="limit">Itens por pagina (max 100) (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WebhookListResponse</returns>
        System.Threading.Tasks.Task<WebhookListResponse> ListWebhooksV1WebhooksGetAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Listar webhooks de alertas
        /// </summary>
        /// <remarks>
        /// Lista webhooks do usuario autenticado (10 alertas). Paginado. Inclui o secret da assinatura da URL (sempre visivel ao dono).
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Pagina (1-indexed) (optional, default to 1)</param>
        /// <param name="limit">Itens por pagina (max 100) (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WebhookListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<WebhookListResponse>> ListWebhooksV1WebhooksGetWithHttpInfoAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Atualizar webhook
        /// </summary>
        /// <remarks>
        /// Atualiza name/url/events/retry_enabled/active do webhook. Eventos validos: 10 alertas.
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="updateWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MessageResponse</returns>
        System.Threading.Tasks.Task<MessageResponse> UpdateWebhookV1WebhooksWebhookIdPutAsync(string webhookId, UpdateWebhookRequest updateWebhookRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Atualizar webhook
        /// </summary>
        /// <remarks>
        /// Atualiza name/url/events/retry_enabled/active do webhook. Eventos validos: 10 alertas.
        /// </remarks>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="updateWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MessageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MessageResponse>> UpdateWebhookV1WebhooksWebhookIdPutWithHttpInfoAsync(string webhookId, UpdateWebhookRequest updateWebhookRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApi : IWebhooksApiSync, IWebhooksApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WebhooksApi : IDisposable, IWebhooksApi
    {
        private FalaAI.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public WebhooksApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public WebhooksApi(string basePath)
        {
            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                new FalaAI.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public WebhooksApi(FalaAI.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WebhooksApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WebhooksApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                new FalaAI.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WebhooksApi(HttpClient client, FalaAI.Api.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = FalaAI.Api.Client.Configuration.MergeConfigurations(
                FalaAI.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new FalaAI.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public WebhooksApi(FalaAI.Api.Client.ISynchronousClient client, FalaAI.Api.Client.IAsynchronousClient asyncClient, FalaAI.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = FalaAI.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public FalaAI.Api.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public FalaAI.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public FalaAI.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public FalaAI.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public FalaAI.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Criar webhook de alertas Cria inscricao para eventos de alerta (10 alertas). Payload enviado: WebhookPayload(event, data, timestamp) com HMAC FalaAI-Signature. Para comprovar a origem, recalcule HMAC-SHA256 de \&quot;timestamp.body\&quot; com seu secret (exemplos: /examples/download/python.zip e nodejs.zip, arquivo webhook_verify).
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createWebhookRequest"></param>
        /// <returns>WebhookItem</returns>
        public WebhookItem CreateWebhookV1WebhooksPost(CreateWebhookRequest createWebhookRequest)
        {
            FalaAI.Api.Client.ApiResponse<WebhookItem> localVarResponse = CreateWebhookV1WebhooksPostWithHttpInfo(createWebhookRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Criar webhook de alertas Cria inscricao para eventos de alerta (10 alertas). Payload enviado: WebhookPayload(event, data, timestamp) com HMAC FalaAI-Signature. Para comprovar a origem, recalcule HMAC-SHA256 de \&quot;timestamp.body\&quot; com seu secret (exemplos: /examples/download/python.zip e nodejs.zip, arquivo webhook_verify).
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createWebhookRequest"></param>
        /// <returns>ApiResponse of WebhookItem</returns>
        public FalaAI.Api.Client.ApiResponse<WebhookItem> CreateWebhookV1WebhooksPostWithHttpInfo(CreateWebhookRequest createWebhookRequest)
        {
            // verify the required parameter 'createWebhookRequest' is set
            if (createWebhookRequest == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'createWebhookRequest' when calling WebhooksApi->CreateWebhookV1WebhooksPost");

            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createWebhookRequest;

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<WebhookItem>("/v1/webhooks", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateWebhookV1WebhooksPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Criar webhook de alertas Cria inscricao para eventos de alerta (10 alertas). Payload enviado: WebhookPayload(event, data, timestamp) com HMAC FalaAI-Signature. Para comprovar a origem, recalcule HMAC-SHA256 de \&quot;timestamp.body\&quot; com seu secret (exemplos: /examples/download/python.zip e nodejs.zip, arquivo webhook_verify).
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WebhookItem</returns>
        public async System.Threading.Tasks.Task<WebhookItem> CreateWebhookV1WebhooksPostAsync(CreateWebhookRequest createWebhookRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            FalaAI.Api.Client.ApiResponse<WebhookItem> localVarResponse = await CreateWebhookV1WebhooksPostWithHttpInfoAsync(createWebhookRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Criar webhook de alertas Cria inscricao para eventos de alerta (10 alertas). Payload enviado: WebhookPayload(event, data, timestamp) com HMAC FalaAI-Signature. Para comprovar a origem, recalcule HMAC-SHA256 de \&quot;timestamp.body\&quot; com seu secret (exemplos: /examples/download/python.zip e nodejs.zip, arquivo webhook_verify).
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WebhookItem)</returns>
        public async System.Threading.Tasks.Task<FalaAI.Api.Client.ApiResponse<WebhookItem>> CreateWebhookV1WebhooksPostWithHttpInfoAsync(CreateWebhookRequest createWebhookRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createWebhookRequest' is set
            if (createWebhookRequest == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'createWebhookRequest' when calling WebhooksApi->CreateWebhookV1WebhooksPost");


            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createWebhookRequest;

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<WebhookItem>("/v1/webhooks", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateWebhookV1WebhooksPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Remover webhook Remove inscricao de webhook por ID.
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <returns>MessageResponse</returns>
        public MessageResponse DeleteWebhookV1WebhooksWebhookIdDelete(string webhookId)
        {
            FalaAI.Api.Client.ApiResponse<MessageResponse> localVarResponse = DeleteWebhookV1WebhooksWebhookIdDeleteWithHttpInfo(webhookId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Remover webhook Remove inscricao de webhook por ID.
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <returns>ApiResponse of MessageResponse</returns>
        public FalaAI.Api.Client.ApiResponse<MessageResponse> DeleteWebhookV1WebhooksWebhookIdDeleteWithHttpInfo(string webhookId)
        {
            // verify the required parameter 'webhookId' is set
            if (webhookId == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'webhookId' when calling WebhooksApi->DeleteWebhookV1WebhooksWebhookIdDelete");

            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("webhook_id", FalaAI.Api.Client.ClientUtils.ParameterToString(webhookId)); // path parameter

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<MessageResponse>("/v1/webhooks/{webhook_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteWebhookV1WebhooksWebhookIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Remover webhook Remove inscricao de webhook por ID.
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MessageResponse</returns>
        public async System.Threading.Tasks.Task<MessageResponse> DeleteWebhookV1WebhooksWebhookIdDeleteAsync(string webhookId, System.Threading.CancellationToken cancellationToken = default)
        {
            FalaAI.Api.Client.ApiResponse<MessageResponse> localVarResponse = await DeleteWebhookV1WebhooksWebhookIdDeleteWithHttpInfoAsync(webhookId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Remover webhook Remove inscricao de webhook por ID.
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MessageResponse)</returns>
        public async System.Threading.Tasks.Task<FalaAI.Api.Client.ApiResponse<MessageResponse>> DeleteWebhookV1WebhooksWebhookIdDeleteWithHttpInfoAsync(string webhookId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'webhookId' is set
            if (webhookId == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'webhookId' when calling WebhooksApi->DeleteWebhookV1WebhooksWebhookIdDelete");


            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("webhook_id", FalaAI.Api.Client.ClientUtils.ParameterToString(webhookId)); // path parameter

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<MessageResponse>("/v1/webhooks/{webhook_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteWebhookV1WebhooksWebhookIdDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Listar webhooks de alertas Lista webhooks do usuario autenticado (10 alertas). Paginado. Inclui o secret da assinatura da URL (sempre visivel ao dono).
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Pagina (1-indexed) (optional, default to 1)</param>
        /// <param name="limit">Itens por pagina (max 100) (optional, default to 20)</param>
        /// <returns>WebhookListResponse</returns>
        public WebhookListResponse ListWebhooksV1WebhooksGet(int? page = default, int? limit = default)
        {
            FalaAI.Api.Client.ApiResponse<WebhookListResponse> localVarResponse = ListWebhooksV1WebhooksGetWithHttpInfo(page, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Listar webhooks de alertas Lista webhooks do usuario autenticado (10 alertas). Paginado. Inclui o secret da assinatura da URL (sempre visivel ao dono).
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Pagina (1-indexed) (optional, default to 1)</param>
        /// <param name="limit">Itens por pagina (max 100) (optional, default to 20)</param>
        /// <returns>ApiResponse of WebhookListResponse</returns>
        public FalaAI.Api.Client.ApiResponse<WebhookListResponse> ListWebhooksV1WebhooksGetWithHttpInfo(int? page = default, int? limit = default)
        {
            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<WebhookListResponse>("/v1/webhooks", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListWebhooksV1WebhooksGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Listar webhooks de alertas Lista webhooks do usuario autenticado (10 alertas). Paginado. Inclui o secret da assinatura da URL (sempre visivel ao dono).
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Pagina (1-indexed) (optional, default to 1)</param>
        /// <param name="limit">Itens por pagina (max 100) (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WebhookListResponse</returns>
        public async System.Threading.Tasks.Task<WebhookListResponse> ListWebhooksV1WebhooksGetAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default)
        {
            FalaAI.Api.Client.ApiResponse<WebhookListResponse> localVarResponse = await ListWebhooksV1WebhooksGetWithHttpInfoAsync(page, limit, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Listar webhooks de alertas Lista webhooks do usuario autenticado (10 alertas). Paginado. Inclui o secret da assinatura da URL (sempre visivel ao dono).
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Pagina (1-indexed) (optional, default to 1)</param>
        /// <param name="limit">Itens por pagina (max 100) (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WebhookListResponse)</returns>
        public async System.Threading.Tasks.Task<FalaAI.Api.Client.ApiResponse<WebhookListResponse>> ListWebhooksV1WebhooksGetWithHttpInfoAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default)
        {

            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(FalaAI.Api.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<WebhookListResponse>("/v1/webhooks", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListWebhooksV1WebhooksGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Atualizar webhook Atualiza name/url/events/retry_enabled/active do webhook. Eventos validos: 10 alertas.
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="updateWebhookRequest"></param>
        /// <returns>MessageResponse</returns>
        public MessageResponse UpdateWebhookV1WebhooksWebhookIdPut(string webhookId, UpdateWebhookRequest updateWebhookRequest)
        {
            FalaAI.Api.Client.ApiResponse<MessageResponse> localVarResponse = UpdateWebhookV1WebhooksWebhookIdPutWithHttpInfo(webhookId, updateWebhookRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Atualizar webhook Atualiza name/url/events/retry_enabled/active do webhook. Eventos validos: 10 alertas.
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="updateWebhookRequest"></param>
        /// <returns>ApiResponse of MessageResponse</returns>
        public FalaAI.Api.Client.ApiResponse<MessageResponse> UpdateWebhookV1WebhooksWebhookIdPutWithHttpInfo(string webhookId, UpdateWebhookRequest updateWebhookRequest)
        {
            // verify the required parameter 'webhookId' is set
            if (webhookId == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'webhookId' when calling WebhooksApi->UpdateWebhookV1WebhooksWebhookIdPut");

            // verify the required parameter 'updateWebhookRequest' is set
            if (updateWebhookRequest == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'updateWebhookRequest' when calling WebhooksApi->UpdateWebhookV1WebhooksWebhookIdPut");

            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("webhook_id", FalaAI.Api.Client.ClientUtils.ParameterToString(webhookId)); // path parameter
            localVarRequestOptions.Data = updateWebhookRequest;

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<MessageResponse>("/v1/webhooks/{webhook_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateWebhookV1WebhooksWebhookIdPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Atualizar webhook Atualiza name/url/events/retry_enabled/active do webhook. Eventos validos: 10 alertas.
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="updateWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MessageResponse</returns>
        public async System.Threading.Tasks.Task<MessageResponse> UpdateWebhookV1WebhooksWebhookIdPutAsync(string webhookId, UpdateWebhookRequest updateWebhookRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            FalaAI.Api.Client.ApiResponse<MessageResponse> localVarResponse = await UpdateWebhookV1WebhooksWebhookIdPutWithHttpInfoAsync(webhookId, updateWebhookRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Atualizar webhook Atualiza name/url/events/retry_enabled/active do webhook. Eventos validos: 10 alertas.
        /// </summary>
        /// <exception cref="FalaAI.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookId"></param>
        /// <param name="updateWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MessageResponse)</returns>
        public async System.Threading.Tasks.Task<FalaAI.Api.Client.ApiResponse<MessageResponse>> UpdateWebhookV1WebhooksWebhookIdPutWithHttpInfoAsync(string webhookId, UpdateWebhookRequest updateWebhookRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'webhookId' is set
            if (webhookId == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'webhookId' when calling WebhooksApi->UpdateWebhookV1WebhooksWebhookIdPut");

            // verify the required parameter 'updateWebhookRequest' is set
            if (updateWebhookRequest == null)
                throw new FalaAI.Api.Client.ApiException(400, "Missing required parameter 'updateWebhookRequest' when calling WebhooksApi->UpdateWebhookV1WebhooksWebhookIdPut");


            FalaAI.Api.Client.RequestOptions localVarRequestOptions = new FalaAI.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = FalaAI.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = FalaAI.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("webhook_id", FalaAI.Api.Client.ClientUtils.ParameterToString(webhookId)); // path parameter
            localVarRequestOptions.Data = updateWebhookRequest;

            // authentication (ApiKeyAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<MessageResponse>("/v1/webhooks/{webhook_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateWebhookV1WebhooksWebhookIdPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
