/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AuditoriaRiscoAnalysisV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuditoriaRiscoAnalysisV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuditoriaRiscoAnalysisV2
        //private AuditoriaRiscoAnalysisV2 instance;

        public AuditoriaRiscoAnalysisV2Tests()
        {
            // TODO uncomment below to create an instance of AuditoriaRiscoAnalysisV2
            //instance = new AuditoriaRiscoAnalysisV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuditoriaRiscoAnalysisV2
        /// </summary>
        [Fact]
        public void AuditoriaRiscoAnalysisV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" AuditoriaRiscoAnalysisV2
            //Assert.IsType<AuditoriaRiscoAnalysisV2>(instance);
        }

        /// <summary>
        /// Test the property 'GlobalMetrics'
        /// </summary>
        [Fact]
        public void GlobalMetricsTest()
        {
            // TODO unit test for the property 'GlobalMetrics'
        }

        /// <summary>
        /// Test the property 'FinalAnalysis'
        /// </summary>
        [Fact]
        public void FinalAnalysisTest()
        {
            // TODO unit test for the property 'FinalAnalysis'
        }

        /// <summary>
        /// Test the property 'Frameworks'
        /// </summary>
        [Fact]
        public void FrameworksTest()
        {
            // TODO unit test for the property 'Frameworks'
        }
    }
}
