/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AudioInputMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AudioInputMetaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AudioInputMeta
        //private AudioInputMeta instance;

        public AudioInputMetaTests()
        {
            // TODO uncomment below to create an instance of AudioInputMeta
            //instance = new AudioInputMeta();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AudioInputMeta
        /// </summary>
        [Fact]
        public void AudioInputMetaInstanceTest()
        {
            // TODO uncomment below to test "IsType" AudioInputMeta
            //Assert.IsType<AudioInputMeta>(instance);
        }

        /// <summary>
        /// Test the property 'DurationS'
        /// </summary>
        [Fact]
        public void DurationSTest()
        {
            // TODO unit test for the property 'DurationS'
        }

        /// <summary>
        /// Test the property 'OriginalFormat'
        /// </summary>
        [Fact]
        public void OriginalFormatTest()
        {
            // TODO unit test for the property 'OriginalFormat'
        }

        /// <summary>
        /// Test the property 'Codec'
        /// </summary>
        [Fact]
        public void CodecTest()
        {
            // TODO unit test for the property 'Codec'
        }

        /// <summary>
        /// Test the property 'SampleRate'
        /// </summary>
        [Fact]
        public void SampleRateTest()
        {
            // TODO unit test for the property 'SampleRate'
        }

        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Fact]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }
    }
}
