/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api.fala.ai' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AuditoriaRiscoV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuditoriaRiscoV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuditoriaRiscoV2
        //private AuditoriaRiscoV2 instance;

        public AuditoriaRiscoV2Tests()
        {
            // TODO uncomment below to create an instance of AuditoriaRiscoV2
            //instance = new AuditoriaRiscoV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuditoriaRiscoV2
        /// </summary>
        [Fact]
        public void AuditoriaRiscoV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" AuditoriaRiscoV2
            //Assert.IsType<AuditoriaRiscoV2>(instance);
        }

        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

        /// <summary>
        /// Test the property 'Participants'
        /// </summary>
        [Fact]
        public void ParticipantsTest()
        {
            // TODO unit test for the property 'Participants'
        }

        /// <summary>
        /// Test the property 'Verdict'
        /// </summary>
        [Fact]
        public void VerdictTest()
        {
            // TODO unit test for the property 'Verdict'
        }

        /// <summary>
        /// Test the property 'Scores'
        /// </summary>
        [Fact]
        public void ScoresTest()
        {
            // TODO unit test for the property 'Scores'
        }

        /// <summary>
        /// Test the property 'Detections'
        /// </summary>
        [Fact]
        public void DetectionsTest()
        {
            // TODO unit test for the property 'Detections'
        }

        /// <summary>
        /// Test the property 'Analysis'
        /// </summary>
        [Fact]
        public void AnalysisTest()
        {
            // TODO unit test for the property 'Analysis'
        }

        /// <summary>
        /// Test the property 'Timeline'
        /// </summary>
        [Fact]
        public void TimelineTest()
        {
            // TODO unit test for the property 'Timeline'
        }

        /// <summary>
        /// Test the property 'AudioEventModel'
        /// </summary>
        [Fact]
        public void AudioEventModelTest()
        {
            // TODO unit test for the property 'AudioEventModel'
        }

        /// <summary>
        /// Test the property 'CategoriesSummary'
        /// </summary>
        [Fact]
        public void CategoriesSummaryTest()
        {
            // TODO unit test for the property 'CategoriesSummary'
        }

        /// <summary>
        /// Test the property 'Indexer'
        /// </summary>
        [Fact]
        public void IndexerTest()
        {
            // TODO unit test for the property 'Indexer'
        }

        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

        /// <summary>
        /// Test the property 'AcoesI18n'
        /// </summary>
        [Fact]
        public void AcoesI18nTest()
        {
            // TODO unit test for the property 'AcoesI18n'
        }

        /// <summary>
        /// Test the property 'AuditDecisions'
        /// </summary>
        [Fact]
        public void AuditDecisionsTest()
        {
            // TODO unit test for the property 'AuditDecisions'
        }

        /// <summary>
        /// Test the property 'ScoringExplanation'
        /// </summary>
        [Fact]
        public void ScoringExplanationTest()
        {
            // TODO unit test for the property 'ScoringExplanation'
        }

        /// <summary>
        /// Test the property 'HtmlReport'
        /// </summary>
        [Fact]
        public void HtmlReportTest()
        {
            // TODO unit test for the property 'HtmlReport'
        }
    }
}
