/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing AuditoriaRiscoSummaryV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuditoriaRiscoSummaryV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuditoriaRiscoSummaryV2
        //private AuditoriaRiscoSummaryV2 instance;

        public AuditoriaRiscoSummaryV2Tests()
        {
            // TODO uncomment below to create an instance of AuditoriaRiscoSummaryV2
            //instance = new AuditoriaRiscoSummaryV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuditoriaRiscoSummaryV2
        /// </summary>
        [Fact]
        public void AuditoriaRiscoSummaryV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" AuditoriaRiscoSummaryV2
            //Assert.IsType<AuditoriaRiscoSummaryV2>(instance);
        }

        /// <summary>
        /// Test the property 'TotalTurns'
        /// </summary>
        [Fact]
        public void TotalTurnsTest()
        {
            // TODO unit test for the property 'TotalTurns'
        }

        /// <summary>
        /// Test the property 'TotalCalibrated'
        /// </summary>
        [Fact]
        public void TotalCalibratedTest()
        {
            // TODO unit test for the property 'TotalCalibrated'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'Tolerated'
        /// </summary>
        [Fact]
        public void ToleratedTest()
        {
            // TODO unit test for the property 'Tolerated'
        }

        /// <summary>
        /// Test the property 'Blocked'
        /// </summary>
        [Fact]
        public void BlockedTest()
        {
            // TODO unit test for the property 'Blocked'
        }

        /// <summary>
        /// Test the property 'AudioEventsUsed'
        /// </summary>
        [Fact]
        public void AudioEventsUsedTest()
        {
            // TODO unit test for the property 'AudioEventsUsed'
        }

        /// <summary>
        /// Test the property 'AudioEventsAggravated'
        /// </summary>
        [Fact]
        public void AudioEventsAggravatedTest()
        {
            // TODO unit test for the property 'AudioEventsAggravated'
        }

        /// <summary>
        /// Test the property 'MacAudioApplied'
        /// </summary>
        [Fact]
        public void MacAudioAppliedTest()
        {
            // TODO unit test for the property 'MacAudioApplied'
        }

        /// <summary>
        /// Test the property 'MvadApplied'
        /// </summary>
        [Fact]
        public void MvadAppliedTest()
        {
            // TODO unit test for the property 'MvadApplied'
        }

        /// <summary>
        /// Test the property 'TotalParticipants'
        /// </summary>
        [Fact]
        public void TotalParticipantsTest()
        {
            // TODO unit test for the property 'TotalParticipants'
        }

        /// <summary>
        /// Test the property 'TotalAgents'
        /// </summary>
        [Fact]
        public void TotalAgentsTest()
        {
            // TODO unit test for the property 'TotalAgents'
        }

        /// <summary>
        /// Test the property 'TotalClients'
        /// </summary>
        [Fact]
        public void TotalClientsTest()
        {
            // TODO unit test for the property 'TotalClients'
        }

        /// <summary>
        /// Test the property 'TotalBots'
        /// </summary>
        [Fact]
        public void TotalBotsTest()
        {
            // TODO unit test for the property 'TotalBots'
        }

        /// <summary>
        /// Test the property 'TotalUnknown'
        /// </summary>
        [Fact]
        public void TotalUnknownTest()
        {
            // TODO unit test for the property 'TotalUnknown'
        }

        /// <summary>
        /// Test the property 'ClientRiskAlertsCount'
        /// </summary>
        [Fact]
        public void ClientRiskAlertsCountTest()
        {
            // TODO unit test for the property 'ClientRiskAlertsCount'
        }

        /// <summary>
        /// Test the property 'ClientBehaviorAlertsCount'
        /// </summary>
        [Fact]
        public void ClientBehaviorAlertsCountTest()
        {
            // TODO unit test for the property 'ClientBehaviorAlertsCount'
        }
    }
}
