/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing DiagnosticResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DiagnosticResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DiagnosticResponse
        //private DiagnosticResponse instance;

        public DiagnosticResponseTests()
        {
            // TODO uncomment below to create an instance of DiagnosticResponse
            //instance = new DiagnosticResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DiagnosticResponse
        /// </summary>
        [Fact]
        public void DiagnosticResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DiagnosticResponse
            //Assert.IsType<DiagnosticResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ResponseLanguage'
        /// </summary>
        [Fact]
        public void ResponseLanguageTest()
        {
            // TODO unit test for the property 'ResponseLanguage'
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'Analysis'
        /// </summary>
        [Fact]
        public void AnalysisTest()
        {
            // TODO unit test for the property 'Analysis'
        }

        /// <summary>
        /// Test the property 'Usage'
        /// </summary>
        [Fact]
        public void UsageTest()
        {
            // TODO unit test for the property 'Usage'
        }

        /// <summary>
        /// Test the property 'ClientReferenceId'
        /// </summary>
        [Fact]
        public void ClientReferenceIdTest()
        {
            // TODO unit test for the property 'ClientReferenceId'
        }
    }
}
