/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing DiagnosticParticipant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DiagnosticParticipantTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DiagnosticParticipant
        //private DiagnosticParticipant instance;

        public DiagnosticParticipantTests()
        {
            // TODO uncomment below to create an instance of DiagnosticParticipant
            //instance = new DiagnosticParticipant();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DiagnosticParticipant
        /// </summary>
        [Fact]
        public void DiagnosticParticipantInstanceTest()
        {
            // TODO uncomment below to test "IsType" DiagnosticParticipant
            //Assert.IsType<DiagnosticParticipant>(instance);
        }

        /// <summary>
        /// Test the property 'Interlocutor'
        /// </summary>
        [Fact]
        public void InterlocutorTest()
        {
            // TODO unit test for the property 'Interlocutor'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
    }
}
