/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing HealthResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HealthResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HealthResponse
        //private HealthResponse instance;

        public HealthResponseTests()
        {
            // TODO uncomment below to create an instance of HealthResponse
            //instance = new HealthResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthResponse
        /// </summary>
        [Fact]
        public void HealthResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" HealthResponse
            //Assert.IsType<HealthResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'UptimeSeconds'
        /// </summary>
        [Fact]
        public void UptimeSecondsTest()
        {
            // TODO unit test for the property 'UptimeSeconds'
        }

        /// <summary>
        /// Test the property 'Database'
        /// </summary>
        [Fact]
        public void DatabaseTest()
        {
            // TODO unit test for the property 'Database'
        }

        /// <summary>
        /// Test the property 'Phase'
        /// </summary>
        [Fact]
        public void PhaseTest()
        {
            // TODO unit test for the property 'Phase'
        }

        /// <summary>
        /// Test the property 'LaunchDate'
        /// </summary>
        [Fact]
        public void LaunchDateTest()
        {
            // TODO unit test for the property 'LaunchDate'
        }
    }
}
