/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ParticipantDiagnostic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParticipantDiagnosticTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ParticipantDiagnostic
        //private ParticipantDiagnostic instance;

        public ParticipantDiagnosticTests()
        {
            // TODO uncomment below to create an instance of ParticipantDiagnostic
            //instance = new ParticipantDiagnostic();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ParticipantDiagnostic
        /// </summary>
        [Fact]
        public void ParticipantDiagnosticInstanceTest()
        {
            // TODO uncomment below to test "IsType" ParticipantDiagnostic
            //Assert.IsType<ParticipantDiagnostic>(instance);
        }

        /// <summary>
        /// Test the property 'Interlocutor'
        /// </summary>
        [Fact]
        public void InterlocutorTest()
        {
            // TODO unit test for the property 'Interlocutor'
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Confidence'
        /// </summary>
        [Fact]
        public void ConfidenceTest()
        {
            // TODO unit test for the property 'Confidence'
        }

        /// <summary>
        /// Test the property 'Evidence'
        /// </summary>
        [Fact]
        public void EvidenceTest()
        {
            // TODO unit test for the property 'Evidence'
        }
    }
}
