/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing RiskAuditScoresV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RiskAuditScoresV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RiskAuditScoresV2
        //private RiskAuditScoresV2 instance;

        public RiskAuditScoresV2Tests()
        {
            // TODO uncomment below to create an instance of RiskAuditScoresV2
            //instance = new RiskAuditScoresV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RiskAuditScoresV2
        /// </summary>
        [Fact]
        public void RiskAuditScoresV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" RiskAuditScoresV2
            //Assert.IsType<RiskAuditScoresV2>(instance);
        }

        /// <summary>
        /// Test the property 'Conversation'
        /// </summary>
        [Fact]
        public void ConversationTest()
        {
            // TODO unit test for the property 'Conversation'
        }

        /// <summary>
        /// Test the property 'PerParticipant'
        /// </summary>
        [Fact]
        public void PerParticipantTest()
        {
            // TODO unit test for the property 'PerParticipant'
        }
    }
}
