/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing RiskAuditAppliedActionV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RiskAuditAppliedActionV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RiskAuditAppliedActionV2
        //private RiskAuditAppliedActionV2 instance;

        public RiskAuditAppliedActionV2Tests()
        {
            // TODO uncomment below to create an instance of RiskAuditAppliedActionV2
            //instance = new RiskAuditAppliedActionV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RiskAuditAppliedActionV2
        /// </summary>
        [Fact]
        public void RiskAuditAppliedActionV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" RiskAuditAppliedActionV2
            //Assert.IsType<RiskAuditAppliedActionV2>(instance);
        }

        /// <summary>
        /// Test the property 'ActionType'
        /// </summary>
        [Fact]
        public void ActionTypeTest()
        {
            // TODO unit test for the property 'ActionType'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Fact]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
    }
}
