/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing RiskAuditVerdictV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RiskAuditVerdictV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RiskAuditVerdictV2
        //private RiskAuditVerdictV2 instance;

        public RiskAuditVerdictV2Tests()
        {
            // TODO uncomment below to create an instance of RiskAuditVerdictV2
            //instance = new RiskAuditVerdictV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RiskAuditVerdictV2
        /// </summary>
        [Fact]
        public void RiskAuditVerdictV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" RiskAuditVerdictV2
            //Assert.IsType<RiskAuditVerdictV2>(instance);
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'LevelCode'
        /// </summary>
        [Fact]
        public void LevelCodeTest()
        {
            // TODO unit test for the property 'LevelCode'
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Fact]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }

        /// <summary>
        /// Test the property 'RiskMatrix'
        /// </summary>
        [Fact]
        public void RiskMatrixTest()
        {
            // TODO unit test for the property 'RiskMatrix'
        }

        /// <summary>
        /// Test the property 'AppliedActions'
        /// </summary>
        [Fact]
        public void AppliedActionsTest()
        {
            // TODO unit test for the property 'AppliedActions'
        }

        /// <summary>
        /// Test the property 'DecisionDetails'
        /// </summary>
        [Fact]
        public void DecisionDetailsTest()
        {
            // TODO unit test for the property 'DecisionDetails'
        }
    }
}
