/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing RiskAuditV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RiskAuditV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RiskAuditV2
        //private RiskAuditV2 instance;

        public RiskAuditV2Tests()
        {
            // TODO uncomment below to create an instance of RiskAuditV2
            //instance = new RiskAuditV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RiskAuditV2
        /// </summary>
        [Fact]
        public void RiskAuditV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" RiskAuditV2
            //Assert.IsType<RiskAuditV2>(instance);
        }

        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

        /// <summary>
        /// Test the property 'Participants'
        /// </summary>
        [Fact]
        public void ParticipantsTest()
        {
            // TODO unit test for the property 'Participants'
        }

        /// <summary>
        /// Test the property 'Verdict'
        /// </summary>
        [Fact]
        public void VerdictTest()
        {
            // TODO unit test for the property 'Verdict'
        }

        /// <summary>
        /// Test the property 'Scores'
        /// </summary>
        [Fact]
        public void ScoresTest()
        {
            // TODO unit test for the property 'Scores'
        }

        /// <summary>
        /// Test the property 'Detections'
        /// </summary>
        [Fact]
        public void DetectionsTest()
        {
            // TODO unit test for the property 'Detections'
        }

        /// <summary>
        /// Test the property 'Analysis'
        /// </summary>
        [Fact]
        public void AnalysisTest()
        {
            // TODO unit test for the property 'Analysis'
        }

        /// <summary>
        /// Test the property 'Timeline'
        /// </summary>
        [Fact]
        public void TimelineTest()
        {
            // TODO unit test for the property 'Timeline'
        }

        /// <summary>
        /// Test the property 'AudioEventModel'
        /// </summary>
        [Fact]
        public void AudioEventModelTest()
        {
            // TODO unit test for the property 'AudioEventModel'
        }

        /// <summary>
        /// Test the property 'CategoriesSummary'
        /// </summary>
        [Fact]
        public void CategoriesSummaryTest()
        {
            // TODO unit test for the property 'CategoriesSummary'
        }

        /// <summary>
        /// Test the property 'Indexer'
        /// </summary>
        [Fact]
        public void IndexerTest()
        {
            // TODO unit test for the property 'Indexer'
        }

        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

        /// <summary>
        /// Test the property 'ActionsI18n'
        /// </summary>
        [Fact]
        public void ActionsI18nTest()
        {
            // TODO unit test for the property 'ActionsI18n'
        }

        /// <summary>
        /// Test the property 'AuditDecisions'
        /// </summary>
        [Fact]
        public void AuditDecisionsTest()
        {
            // TODO unit test for the property 'AuditDecisions'
        }

        /// <summary>
        /// Test the property 'ScoringExplanation'
        /// </summary>
        [Fact]
        public void ScoringExplanationTest()
        {
            // TODO unit test for the property 'ScoringExplanation'
        }

        /// <summary>
        /// Test the property 'HtmlReport'
        /// </summary>
        [Fact]
        public void HtmlReportTest()
        {
            // TODO unit test for the property 'HtmlReport'
        }
    }
}
