/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing RiskAuditV2Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RiskAuditV2ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RiskAuditV2Response
        //private RiskAuditV2Response instance;

        public RiskAuditV2ResponseTests()
        {
            // TODO uncomment below to create an instance of RiskAuditV2Response
            //instance = new RiskAuditV2Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RiskAuditV2Response
        /// </summary>
        [Fact]
        public void RiskAuditV2ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RiskAuditV2Response
            //Assert.IsType<RiskAuditV2Response>(instance);
        }

        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Fact]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }
    }
}
