/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing RiskAuditMetaV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RiskAuditMetaV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RiskAuditMetaV2
        //private RiskAuditMetaV2 instance;

        public RiskAuditMetaV2Tests()
        {
            // TODO uncomment below to create an instance of RiskAuditMetaV2
            //instance = new RiskAuditMetaV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RiskAuditMetaV2
        /// </summary>
        [Fact]
        public void RiskAuditMetaV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" RiskAuditMetaV2
            //Assert.IsType<RiskAuditMetaV2>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'CallDurationS'
        /// </summary>
        [Fact]
        public void CallDurationSTest()
        {
            // TODO unit test for the property 'CallDurationS'
        }

        /// <summary>
        /// Test the property 'AnalyzedAt'
        /// </summary>
        [Fact]
        public void AnalyzedAtTest()
        {
            // TODO unit test for the property 'AnalyzedAt'
        }

        /// <summary>
        /// Test the property 'Usage'
        /// </summary>
        [Fact]
        public void UsageTest()
        {
            // TODO unit test for the property 'Usage'
        }

        /// <summary>
        /// Test the property 'ClientReferenceId'
        /// </summary>
        [Fact]
        public void ClientReferenceIdTest()
        {
            // TODO unit test for the property 'ClientReferenceId'
        }
    }
}
