/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing RiskAuditSummaryV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RiskAuditSummaryV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RiskAuditSummaryV2
        //private RiskAuditSummaryV2 instance;

        public RiskAuditSummaryV2Tests()
        {
            // TODO uncomment below to create an instance of RiskAuditSummaryV2
            //instance = new RiskAuditSummaryV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RiskAuditSummaryV2
        /// </summary>
        [Fact]
        public void RiskAuditSummaryV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" RiskAuditSummaryV2
            //Assert.IsType<RiskAuditSummaryV2>(instance);
        }

        /// <summary>
        /// Test the property 'TotalTurns'
        /// </summary>
        [Fact]
        public void TotalTurnsTest()
        {
            // TODO unit test for the property 'TotalTurns'
        }

        /// <summary>
        /// Test the property 'TotalCalibrated'
        /// </summary>
        [Fact]
        public void TotalCalibratedTest()
        {
            // TODO unit test for the property 'TotalCalibrated'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'Tolerated'
        /// </summary>
        [Fact]
        public void ToleratedTest()
        {
            // TODO unit test for the property 'Tolerated'
        }

        /// <summary>
        /// Test the property 'Blocked'
        /// </summary>
        [Fact]
        public void BlockedTest()
        {
            // TODO unit test for the property 'Blocked'
        }

        /// <summary>
        /// Test the property 'AudioEventsUsed'
        /// </summary>
        [Fact]
        public void AudioEventsUsedTest()
        {
            // TODO unit test for the property 'AudioEventsUsed'
        }

        /// <summary>
        /// Test the property 'AudioEventsAggravated'
        /// </summary>
        [Fact]
        public void AudioEventsAggravatedTest()
        {
            // TODO unit test for the property 'AudioEventsAggravated'
        }

        /// <summary>
        /// Test the property 'MacAudioApplied'
        /// </summary>
        [Fact]
        public void MacAudioAppliedTest()
        {
            // TODO unit test for the property 'MacAudioApplied'
        }

        /// <summary>
        /// Test the property 'MvadApplied'
        /// </summary>
        [Fact]
        public void MvadAppliedTest()
        {
            // TODO unit test for the property 'MvadApplied'
        }

        /// <summary>
        /// Test the property 'TotalParticipants'
        /// </summary>
        [Fact]
        public void TotalParticipantsTest()
        {
            // TODO unit test for the property 'TotalParticipants'
        }

        /// <summary>
        /// Test the property 'TotalAgents'
        /// </summary>
        [Fact]
        public void TotalAgentsTest()
        {
            // TODO unit test for the property 'TotalAgents'
        }

        /// <summary>
        /// Test the property 'TotalClients'
        /// </summary>
        [Fact]
        public void TotalClientsTest()
        {
            // TODO unit test for the property 'TotalClients'
        }

        /// <summary>
        /// Test the property 'TotalBots'
        /// </summary>
        [Fact]
        public void TotalBotsTest()
        {
            // TODO unit test for the property 'TotalBots'
        }

        /// <summary>
        /// Test the property 'TotalUnknown'
        /// </summary>
        [Fact]
        public void TotalUnknownTest()
        {
            // TODO unit test for the property 'TotalUnknown'
        }

        /// <summary>
        /// Test the property 'ClientRiskAlertsCount'
        /// </summary>
        [Fact]
        public void ClientRiskAlertsCountTest()
        {
            // TODO unit test for the property 'ClientRiskAlertsCount'
        }

        /// <summary>
        /// Test the property 'ClientBehaviorAlertsCount'
        /// </summary>
        [Fact]
        public void ClientBehaviorAlertsCountTest()
        {
            // TODO unit test for the property 'ClientBehaviorAlertsCount'
        }
    }
}
