/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing UsageLogItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UsageLogItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UsageLogItem
        //private UsageLogItem instance;

        public UsageLogItemTests()
        {
            // TODO uncomment below to create an instance of UsageLogItem
            //instance = new UsageLogItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UsageLogItem
        /// </summary>
        [Fact]
        public void UsageLogItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" UsageLogItem
            //Assert.IsType<UsageLogItem>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Endpoint'
        /// </summary>
        [Fact]
        public void EndpointTest()
        {
            // TODO unit test for the property 'Endpoint'
        }

        /// <summary>
        /// Test the property 'CreditsCost'
        /// </summary>
        [Fact]
        public void CreditsCostTest()
        {
            // TODO unit test for the property 'CreditsCost'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'ErrorsCount'
        /// </summary>
        [Fact]
        public void ErrorsCountTest()
        {
            // TODO unit test for the property 'ErrorsCount'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
