/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookItem
        //private WebhookItem instance;

        public WebhookItemTests()
        {
            // TODO uncomment below to create an instance of WebhookItem
            //instance = new WebhookItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookItem
        /// </summary>
        [Fact]
        public void WebhookItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookItem
            //Assert.IsType<WebhookItem>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }

        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'RetryEnabled'
        /// </summary>
        [Fact]
        public void RetryEnabledTest()
        {
            // TODO unit test for the property 'RetryEnabled'
        }

        /// <summary>
        /// Test the property 'LastDeliveryAt'
        /// </summary>
        [Fact]
        public void LastDeliveryAtTest()
        {
            // TODO unit test for the property 'LastDeliveryAt'
        }

        /// <summary>
        /// Test the property 'LastStatus'
        /// </summary>
        [Fact]
        public void LastStatusTest()
        {
            // TODO unit test for the property 'LastStatus'
        }

        /// <summary>
        /// Test the property 'FailureCount'
        /// </summary>
        [Fact]
        public void FailureCountTest()
        {
            // TODO unit test for the property 'FailureCount'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
