/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookItem
        //private WebhookItem instance;

        public WebhookItemTests()
        {
            // TODO uncomment below to create an instance of WebhookItem
            //instance = new WebhookItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookItem
        /// </summary>
        [Fact]
        public void WebhookItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookItem
            //Assert.IsType<WebhookItem>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }

        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'RetryEnabled'
        /// </summary>
        [Fact]
        public void RetryEnabledTest()
        {
            // TODO unit test for the property 'RetryEnabled'
        }

        /// <summary>
        /// Test the property 'LastDeliveryAt'
        /// </summary>
        [Fact]
        public void LastDeliveryAtTest()
        {
            // TODO unit test for the property 'LastDeliveryAt'
        }

        /// <summary>
        /// Test the property 'LastStatus'
        /// </summary>
        [Fact]
        public void LastStatusTest()
        {
            // TODO unit test for the property 'LastStatus'
        }

        /// <summary>
        /// Test the property 'FailureCount'
        /// </summary>
        [Fact]
        public void FailureCountTest()
        {
            // TODO unit test for the property 'FailureCount'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
