/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FalaAI.Api.Model;
using FalaAI.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FalaAI.Api.Test.Model
{
    /// <summary>
    ///  Class for testing WhatsappUsage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WhatsappUsageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WhatsappUsage
        //private WhatsappUsage instance;

        public WhatsappUsageTests()
        {
            // TODO uncomment below to create an instance of WhatsappUsage
            //instance = new WhatsappUsage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WhatsappUsage
        /// </summary>
        [Fact]
        public void WhatsappUsageInstanceTest()
        {
            // TODO uncomment below to test "IsType" WhatsappUsage
            //Assert.IsType<WhatsappUsage>(instance);
        }

        /// <summary>
        /// Test the property 'Conversations'
        /// </summary>
        [Fact]
        public void ConversationsTest()
        {
            // TODO unit test for the property 'Conversations'
        }

        /// <summary>
        /// Test the property 'Characters'
        /// </summary>
        [Fact]
        public void CharactersTest()
        {
            // TODO unit test for the property 'Characters'
        }

        /// <summary>
        /// Test the property 'CreditsConsumed'
        /// </summary>
        [Fact]
        public void CreditsConsumedTest()
        {
            // TODO unit test for the property 'CreditsConsumed'
        }

        /// <summary>
        /// Test the property 'ProcessingMs'
        /// </summary>
        [Fact]
        public void ProcessingMsTest()
        {
            // TODO unit test for the property 'ProcessingMs'
        }
    }
}
