/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using FalaAI.Api.Client;
using FalaAI.Api.Api;
// uncomment below to import models
//using FalaAI.Api.Model;

namespace FalaAI.Api.Test.Api
{
    /// <summary>
    ///  Class for testing AnalysisApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AnalysisApiTests : IDisposable
    {
        private AnalysisApi instance;

        public AnalysisApiTests()
        {
            instance = new AnalysisApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalysisApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AnalysisApi
            //Assert.IsType<AnalysisApi>(instance);
        }

        /// <summary>
        /// Test CreateDiagnosticV1AnalyzeDiagnosticPost
        /// </summary>
        [Fact]
        public void CreateDiagnosticV1AnalyzeDiagnosticPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DiagnosticRequest diagnosticRequest = null;
            //var response = instance.CreateDiagnosticV1AnalyzeDiagnosticPost(diagnosticRequest);
            //Assert.IsType<DiagnosticResponse>(response);
        }

        /// <summary>
        /// Test CreateRiskAuditV1AnalyzeRiskAuditPost
        /// </summary>
        [Fact]
        public void CreateRiskAuditV1AnalyzeRiskAuditPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RiskAuditRequest riskAuditRequest = null;
            //var response = instance.CreateRiskAuditV1AnalyzeRiskAuditPost(riskAuditRequest);
            //Assert.IsType<RiskAuditV2Response>(response);
        }
    }
}
