/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using FalaAI.Api.Client;
using FalaAI.Api.Api;
// uncomment below to import models
//using FalaAI.Api.Model;

namespace FalaAI.Api.Test.Api
{
    /// <summary>
    ///  Class for testing EmailAlertsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmailAlertsApiTests : IDisposable
    {
        private EmailAlertsApi instance;

        public EmailAlertsApiTests()
        {
            instance = new EmailAlertsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailAlertsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmailAlertsApi
            //Assert.IsType<EmailAlertsApi>(instance);
        }

        /// <summary>
        /// Test CreateEmailAlertV1EmailAlertsPost
        /// </summary>
        [Fact]
        public void CreateEmailAlertV1EmailAlertsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateEmailAlertRequest createEmailAlertRequest = null;
            //var response = instance.CreateEmailAlertV1EmailAlertsPost(createEmailAlertRequest);
            //Assert.IsType<EmailAlertItem>(response);
        }

        /// <summary>
        /// Test DeleteEmailAlertV1EmailAlertsAlertIdDelete
        /// </summary>
        [Fact]
        public void DeleteEmailAlertV1EmailAlertsAlertIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string alertId = null;
            //var response = instance.DeleteEmailAlertV1EmailAlertsAlertIdDelete(alertId);
            //Assert.IsType<EmailAlertMessageResponse>(response);
        }

        /// <summary>
        /// Test ListEmailAlertsV1EmailAlertsGet
        /// </summary>
        [Fact]
        public void ListEmailAlertsV1EmailAlertsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //var response = instance.ListEmailAlertsV1EmailAlertsGet(page, limit);
            //Assert.IsType<EmailAlertListResponse>(response);
        }

        /// <summary>
        /// Test UpdateEmailAlertV1EmailAlertsAlertIdPut
        /// </summary>
        [Fact]
        public void UpdateEmailAlertV1EmailAlertsAlertIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string alertId = null;
            //UpdateEmailAlertRequest updateEmailAlertRequest = null;
            //var response = instance.UpdateEmailAlertV1EmailAlertsAlertIdPut(alertId, updateEmailAlertRequest);
            //Assert.IsType<EmailAlertMessageResponse>(response);
        }
    }
}
