/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using FalaAI.Api.Client;
using FalaAI.Api.Api;
// uncomment below to import models
//using FalaAI.Api.Model;

namespace FalaAI.Api.Test.Api
{
    /// <summary>
    ///  Class for testing EmailAlertsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmailAlertsApiTests : IDisposable
    {
        private EmailAlertsApi instance;

        public EmailAlertsApiTests()
        {
            instance = new EmailAlertsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailAlertsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmailAlertsApi
            //Assert.IsType<EmailAlertsApi>(instance);
        }

        /// <summary>
        /// Test CreateEmailAlertV1EmailAlertsPost
        /// </summary>
        [Fact]
        public void CreateEmailAlertV1EmailAlertsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateEmailAlertRequest createEmailAlertRequest = null;
            //var response = instance.CreateEmailAlertV1EmailAlertsPost(createEmailAlertRequest);
            //Assert.IsType<EmailAlertItem>(response);
        }

        /// <summary>
        /// Test DeleteEmailAlertV1EmailAlertsAlertIdDelete
        /// </summary>
        [Fact]
        public void DeleteEmailAlertV1EmailAlertsAlertIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string alertId = null;
            //var response = instance.DeleteEmailAlertV1EmailAlertsAlertIdDelete(alertId);
            //Assert.IsType<EmailAlertMessageResponse>(response);
        }

        /// <summary>
        /// Test ListEmailAlertsV1EmailAlertsGet
        /// </summary>
        [Fact]
        public void ListEmailAlertsV1EmailAlertsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //var response = instance.ListEmailAlertsV1EmailAlertsGet(page, limit);
            //Assert.IsType<EmailAlertListResponse>(response);
        }

        /// <summary>
        /// Test UpdateEmailAlertV1EmailAlertsAlertIdPut
        /// </summary>
        [Fact]
        public void UpdateEmailAlertV1EmailAlertsAlertIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string alertId = null;
            //UpdateEmailAlertRequest updateEmailAlertRequest = null;
            //var response = instance.UpdateEmailAlertV1EmailAlertsAlertIdPut(alertId, updateEmailAlertRequest);
            //Assert.IsType<EmailAlertMessageResponse>(response);
        }
    }
}
