/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using FalaAI.Api.Client;
using FalaAI.Api.Api;
// uncomment below to import models
//using FalaAI.Api.Model;

namespace FalaAI.Api.Test.Api
{
    /// <summary>
    ///  Class for testing VersionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class VersionApiTests : IDisposable
    {
        private VersionApi instance;

        public VersionApiTests()
        {
            instance = new VersionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VersionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' VersionApi
            //Assert.IsType<VersionApi>(instance);
        }

        /// <summary>
        /// Test GetVersionApiVersionGet
        /// </summary>
        [Fact]
        public void GetVersionApiVersionGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetVersionApiVersionGet();
            //Assert.IsType<VersionResponse>(response);
        }
    }
}
