/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// AuditoriaRiscoParticipantsV2
    /// </summary>
    [DataContract(Name = "AuditoriaRiscoParticipantsV2")]
    public partial class AuditoriaRiscoParticipantsV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditoriaRiscoParticipantsV2" /> class.
        /// </summary>
        /// <param name="identified">Identified participants.</param>
        /// <param name="callDirection">inbound/outbound.</param>
        /// <param name="roleInferenceReliable">Role inference reliability (default to true).</param>
        /// <param name="identificationStatus">Identification status (default to &quot;none&quot;).</param>
        /// <param name="unidentifiedItemsCount">Unidentified items count (default to 0).</param>
        public AuditoriaRiscoParticipantsV2(List<AuditoriaRiscoParticipantV2> identified = default, string callDirection = default, bool roleInferenceReliable = true, string identificationStatus = @"none", int unidentifiedItemsCount = 0)
        {
            this.Identified = identified;
            this.CallDirection = callDirection;
            this.RoleInferenceReliable = roleInferenceReliable;
            // use default value if no "identificationStatus" provided
            this.IdentificationStatus = identificationStatus ?? @"none";
            this.UnidentifiedItemsCount = unidentifiedItemsCount;
        }

        /// <summary>
        /// Identified participants
        /// </summary>
        /// <value>Identified participants</value>
        [DataMember(Name = "identified", EmitDefaultValue = false)]
        public List<AuditoriaRiscoParticipantV2> Identified { get; set; }

        /// <summary>
        /// inbound/outbound
        /// </summary>
        /// <value>inbound/outbound</value>
        [DataMember(Name = "call_direction", EmitDefaultValue = true)]
        public string CallDirection { get; set; }

        /// <summary>
        /// Role inference reliability
        /// </summary>
        /// <value>Role inference reliability</value>
        [DataMember(Name = "role_inference_reliable", EmitDefaultValue = true)]
        public bool RoleInferenceReliable { get; set; }

        /// <summary>
        /// Identification status
        /// </summary>
        /// <value>Identification status</value>
        [DataMember(Name = "identification_status", EmitDefaultValue = false)]
        public string IdentificationStatus { get; set; }

        /// <summary>
        /// Unidentified items count
        /// </summary>
        /// <value>Unidentified items count</value>
        [DataMember(Name = "unidentified_items_count", EmitDefaultValue = false)]
        public int UnidentifiedItemsCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuditoriaRiscoParticipantsV2 {\n");
            sb.Append("  Identified: ").Append(Identified).Append("\n");
            sb.Append("  CallDirection: ").Append(CallDirection).Append("\n");
            sb.Append("  RoleInferenceReliable: ").Append(RoleInferenceReliable).Append("\n");
            sb.Append("  IdentificationStatus: ").Append(IdentificationStatus).Append("\n");
            sb.Append("  UnidentifiedItemsCount: ").Append(UnidentifiedItemsCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
