/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// AudioInputMeta
    /// </summary>
    [DataContract(Name = "AudioInputMeta")]
    public partial class AudioInputMeta : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioInputMeta" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AudioInputMeta() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioInputMeta" /> class.
        /// </summary>
        /// <param name="durationS">Exact audio duration sent in seconds (required).</param>
        /// <param name="originalFormat">Original file format (wav, mp3, ogg, etc) (required).</param>
        /// <param name="codec">Audio codec sent (required).</param>
        /// <param name="sampleRate">Audio sample rate in Hz (required).</param>
        /// <param name="channels">Number of channels (1&#x3D;mono, 2&#x3D;stereo) (required).</param>
        public AudioInputMeta(decimal durationS = default, string originalFormat = default, string codec = default, int sampleRate = default, int channels = default)
        {
            this.DurationS = durationS;
            // to ensure "originalFormat" is required (not null)
            if (originalFormat == null)
            {
                throw new ArgumentNullException("originalFormat is a required property for AudioInputMeta and cannot be null");
            }
            this.OriginalFormat = originalFormat;
            // to ensure "codec" is required (not null)
            if (codec == null)
            {
                throw new ArgumentNullException("codec is a required property for AudioInputMeta and cannot be null");
            }
            this.Codec = codec;
            this.SampleRate = sampleRate;
            this.Channels = channels;
        }

        /// <summary>
        /// Exact audio duration sent in seconds
        /// </summary>
        /// <value>Exact audio duration sent in seconds</value>
        [DataMember(Name = "duration_s", IsRequired = true, EmitDefaultValue = true)]
        public decimal DurationS { get; set; }

        /// <summary>
        /// Original file format (wav, mp3, ogg, etc)
        /// </summary>
        /// <value>Original file format (wav, mp3, ogg, etc)</value>
        [DataMember(Name = "original_format", IsRequired = true, EmitDefaultValue = true)]
        public string OriginalFormat { get; set; }

        /// <summary>
        /// Audio codec sent
        /// </summary>
        /// <value>Audio codec sent</value>
        [DataMember(Name = "codec", IsRequired = true, EmitDefaultValue = true)]
        public string Codec { get; set; }

        /// <summary>
        /// Audio sample rate in Hz
        /// </summary>
        /// <value>Audio sample rate in Hz</value>
        [DataMember(Name = "sample_rate", IsRequired = true, EmitDefaultValue = true)]
        public int SampleRate { get; set; }

        /// <summary>
        /// Number of channels (1&#x3D;mono, 2&#x3D;stereo)
        /// </summary>
        /// <value>Number of channels (1&#x3D;mono, 2&#x3D;stereo)</value>
        [DataMember(Name = "channels", IsRequired = true, EmitDefaultValue = true)]
        public int Channels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AudioInputMeta {\n");
            sb.Append("  DurationS: ").Append(DurationS).Append("\n");
            sb.Append("  OriginalFormat: ").Append(OriginalFormat).Append("\n");
            sb.Append("  Codec: ").Append(Codec).Append("\n");
            sb.Append("  SampleRate: ").Append(SampleRate).Append("\n");
            sb.Append("  Channels: ").Append(Channels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
