/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// Response V2 (build_public_response_v2) â€” blocos logicos EN-US. Fonte: response_builder.py.
    /// </summary>
    [DataContract(Name = "AuditoriaRiscoV2")]
    public partial class AuditoriaRiscoV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditoriaRiscoV2" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuditoriaRiscoV2()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditoriaRiscoV2" /> class.
        /// </summary>
        /// <param name="meta">Identification + usage (required).</param>
        /// <param name="participants">Participants/roles/direction (required).</param>
        /// <param name="verdict">Verdict + level + applied actions (required).</param>
        /// <param name="scores">Consolidated + per-participant scores (required).</param>
        /// <param name="detections">violations/positives/client alerts (required).</param>
        /// <param name="analysis">global_metrics + final_analysis + frameworks (required).</param>
        /// <param name="timeline">turns_sentiment + audio_events + groups (required).</param>
        /// <param name="audioEventModel">MAC audio event semantics (required).</param>
        /// <param name="categoriesSummary">Per-category summary (keyed by category) (required).</param>
        /// <param name="indexer">Suggested terms for bank (required).</param>
        /// <param name="summary">Executive summary counts (required).</param>
        /// <param name="acoesI18n">Used actions i18n catalog (keyed by action) (required).</param>
        /// <param name="auditDecisions">Risk origin + validator changes (required).</param>
        /// <param name="scoringExplanation">Score composition explanation (required).</param>
        /// <param name="htmlReport">HTML report (base64 gzip) (required).</param>
        public AuditoriaRiscoV2(AuditoriaRiscoMetaV2 meta = default, AuditoriaRiscoParticipantsV2 participants = default, AuditoriaRiscoVerdictV2 verdict = default, AuditoriaRiscoScoresV2 scores = default, AuditoriaRiscoDetectionsV2 detections = default, AuditoriaRiscoAnalysisV2 analysis = default, AuditoriaRiscoTimelineV2 timeline = default, AuditoriaRiscoAudioEventModelV2 audioEventModel = default, Dictionary<string, Object> categoriesSummary = default, AuditoriaRiscoIndexerV2 indexer = default, AuditoriaRiscoSummaryV2 summary = default, Dictionary<string, Object> acoesI18n = default, AuditoriaRiscoAuditDecisionsV2 auditDecisions = default, AuditoriaRiscoScoringExplanationV2 scoringExplanation = default, string htmlReport = default)
        {
            // to ensure "meta" is required (not null)
            if (meta == null)
            {
                throw new ArgumentNullException("meta is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.Meta = meta;
            // to ensure "participants" is required (not null)
            if (participants == null)
            {
                throw new ArgumentNullException("participants is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.Participants = participants;
            // to ensure "verdict" is required (not null)
            if (verdict == null)
            {
                throw new ArgumentNullException("verdict is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.Verdict = verdict;
            // to ensure "scores" is required (not null)
            if (scores == null)
            {
                throw new ArgumentNullException("scores is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.Scores = scores;
            // to ensure "detections" is required (not null)
            if (detections == null)
            {
                throw new ArgumentNullException("detections is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.Detections = detections;
            // to ensure "analysis" is required (not null)
            if (analysis == null)
            {
                throw new ArgumentNullException("analysis is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.Analysis = analysis;
            // to ensure "timeline" is required (not null)
            if (timeline == null)
            {
                throw new ArgumentNullException("timeline is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.Timeline = timeline;
            // to ensure "audioEventModel" is required (not null)
            if (audioEventModel == null)
            {
                throw new ArgumentNullException("audioEventModel is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.AudioEventModel = audioEventModel;
            // to ensure "categoriesSummary" is required (not null)
            if (categoriesSummary == null)
            {
                throw new ArgumentNullException("categoriesSummary is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.CategoriesSummary = categoriesSummary;
            // to ensure "indexer" is required (not null)
            if (indexer == null)
            {
                throw new ArgumentNullException("indexer is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.Indexer = indexer;
            // to ensure "summary" is required (not null)
            if (summary == null)
            {
                throw new ArgumentNullException("summary is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.Summary = summary;
            // to ensure "acoesI18n" is required (not null)
            if (acoesI18n == null)
            {
                throw new ArgumentNullException("acoesI18n is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.AcoesI18n = acoesI18n;
            // to ensure "auditDecisions" is required (not null)
            if (auditDecisions == null)
            {
                throw new ArgumentNullException("auditDecisions is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.AuditDecisions = auditDecisions;
            // to ensure "scoringExplanation" is required (not null)
            if (scoringExplanation == null)
            {
                throw new ArgumentNullException("scoringExplanation is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.ScoringExplanation = scoringExplanation;
            // to ensure "htmlReport" is required (not null)
            if (htmlReport == null)
            {
                throw new ArgumentNullException("htmlReport is a required property for AuditoriaRiscoV2 and cannot be null");
            }
            this.HtmlReport = htmlReport;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Identification + usage
        /// </summary>
        /// <value>Identification + usage</value>
        [DataMember(Name = "meta", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoMetaV2 Meta { get; set; }

        /// <summary>
        /// Participants/roles/direction
        /// </summary>
        /// <value>Participants/roles/direction</value>
        [DataMember(Name = "participants", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoParticipantsV2 Participants { get; set; }

        /// <summary>
        /// Verdict + level + applied actions
        /// </summary>
        /// <value>Verdict + level + applied actions</value>
        [DataMember(Name = "verdict", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoVerdictV2 Verdict { get; set; }

        /// <summary>
        /// Consolidated + per-participant scores
        /// </summary>
        /// <value>Consolidated + per-participant scores</value>
        [DataMember(Name = "scores", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoScoresV2 Scores { get; set; }

        /// <summary>
        /// violations/positives/client alerts
        /// </summary>
        /// <value>violations/positives/client alerts</value>
        [DataMember(Name = "detections", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoDetectionsV2 Detections { get; set; }

        /// <summary>
        /// global_metrics + final_analysis + frameworks
        /// </summary>
        /// <value>global_metrics + final_analysis + frameworks</value>
        [DataMember(Name = "analysis", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoAnalysisV2 Analysis { get; set; }

        /// <summary>
        /// turns_sentiment + audio_events + groups
        /// </summary>
        /// <value>turns_sentiment + audio_events + groups</value>
        [DataMember(Name = "timeline", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoTimelineV2 Timeline { get; set; }

        /// <summary>
        /// MAC audio event semantics
        /// </summary>
        /// <value>MAC audio event semantics</value>
        [DataMember(Name = "audio_event_model", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoAudioEventModelV2 AudioEventModel { get; set; }

        /// <summary>
        /// Per-category summary (keyed by category)
        /// </summary>
        /// <value>Per-category summary (keyed by category)</value>
        [DataMember(Name = "categories_summary", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> CategoriesSummary { get; set; }

        /// <summary>
        /// Suggested terms for bank
        /// </summary>
        /// <value>Suggested terms for bank</value>
        [DataMember(Name = "indexer", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoIndexerV2 Indexer { get; set; }

        /// <summary>
        /// Executive summary counts
        /// </summary>
        /// <value>Executive summary counts</value>
        [DataMember(Name = "summary", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoSummaryV2 Summary { get; set; }

        /// <summary>
        /// Used actions i18n catalog (keyed by action)
        /// </summary>
        /// <value>Used actions i18n catalog (keyed by action)</value>
        [DataMember(Name = "acoes_i18n", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> AcoesI18n { get; set; }

        /// <summary>
        /// Risk origin + validator changes
        /// </summary>
        /// <value>Risk origin + validator changes</value>
        [DataMember(Name = "audit_decisions", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoAuditDecisionsV2 AuditDecisions { get; set; }

        /// <summary>
        /// Score composition explanation
        /// </summary>
        /// <value>Score composition explanation</value>
        [DataMember(Name = "scoring_explanation", IsRequired = true, EmitDefaultValue = true)]
        public AuditoriaRiscoScoringExplanationV2 ScoringExplanation { get; set; }

        /// <summary>
        /// HTML report (base64 gzip)
        /// </summary>
        /// <value>HTML report (base64 gzip)</value>
        [DataMember(Name = "html_report", IsRequired = true, EmitDefaultValue = true)]
        public string HtmlReport { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuditoriaRiscoV2 {\n");
            sb.Append("  Meta: ").Append(Meta).Append("\n");
            sb.Append("  Participants: ").Append(Participants).Append("\n");
            sb.Append("  Verdict: ").Append(Verdict).Append("\n");
            sb.Append("  Scores: ").Append(Scores).Append("\n");
            sb.Append("  Detections: ").Append(Detections).Append("\n");
            sb.Append("  Analysis: ").Append(Analysis).Append("\n");
            sb.Append("  Timeline: ").Append(Timeline).Append("\n");
            sb.Append("  AudioEventModel: ").Append(AudioEventModel).Append("\n");
            sb.Append("  CategoriesSummary: ").Append(CategoriesSummary).Append("\n");
            sb.Append("  Indexer: ").Append(Indexer).Append("\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("  AcoesI18n: ").Append(AcoesI18n).Append("\n");
            sb.Append("  AuditDecisions: ").Append(AuditDecisions).Append("\n");
            sb.Append("  ScoringExplanation: ").Append(ScoringExplanation).Append("\n");
            sb.Append("  HtmlReport: ").Append(HtmlReport).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
