/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// AudioEvent
    /// </summary>
    [DataContract(Name = "AudioEvent")]
    public partial class AudioEvent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioEvent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AudioEvent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioEvent" /> class.
        /// </summary>
        /// <param name="varEvent">Type of identified audio event. Ex: [riso], [suspiro], [pausa], [tosse] (required).</param>
        /// <param name="startS">Start time of audio event in seconds (required).</param>
        /// <param name="endS">End time of audio event in seconds (required).</param>
        /// <param name="durationS">Event duration in seconds (required).</param>
        /// <param name="formattedTimestamp">Formatted timestamp HH:MM:SS.mmm of event start (required).</param>
        public AudioEvent(string varEvent = default, decimal startS = default, decimal endS = default, decimal durationS = default, string formattedTimestamp = default)
        {
            // to ensure "varEvent" is required (not null)
            if (varEvent == null)
            {
                throw new ArgumentNullException("varEvent is a required property for AudioEvent and cannot be null");
            }
            this.Event = varEvent;
            this.StartS = startS;
            this.EndS = endS;
            this.DurationS = durationS;
            // to ensure "formattedTimestamp" is required (not null)
            if (formattedTimestamp == null)
            {
                throw new ArgumentNullException("formattedTimestamp is a required property for AudioEvent and cannot be null");
            }
            this.FormattedTimestamp = formattedTimestamp;
        }

        /// <summary>
        /// Type of identified audio event. Ex: [riso], [suspiro], [pausa], [tosse]
        /// </summary>
        /// <value>Type of identified audio event. Ex: [riso], [suspiro], [pausa], [tosse]</value>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = true)]
        public string Event { get; set; }

        /// <summary>
        /// Start time of audio event in seconds
        /// </summary>
        /// <value>Start time of audio event in seconds</value>
        [DataMember(Name = "start_s", IsRequired = true, EmitDefaultValue = true)]
        public decimal StartS { get; set; }

        /// <summary>
        /// End time of audio event in seconds
        /// </summary>
        /// <value>End time of audio event in seconds</value>
        [DataMember(Name = "end_s", IsRequired = true, EmitDefaultValue = true)]
        public decimal EndS { get; set; }

        /// <summary>
        /// Event duration in seconds
        /// </summary>
        /// <value>Event duration in seconds</value>
        [DataMember(Name = "duration_s", IsRequired = true, EmitDefaultValue = true)]
        public decimal DurationS { get; set; }

        /// <summary>
        /// Formatted timestamp HH:MM:SS.mmm of event start
        /// </summary>
        /// <value>Formatted timestamp HH:MM:SS.mmm of event start</value>
        [DataMember(Name = "formatted_timestamp", IsRequired = true, EmitDefaultValue = true)]
        public string FormattedTimestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AudioEvent {\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("  StartS: ").Append(StartS).Append("\n");
            sb.Append("  EndS: ").Append(EndS).Append("\n");
            sb.Append("  DurationS: ").Append(DurationS).Append("\n");
            sb.Append("  FormattedTimestamp: ").Append(FormattedTimestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
