/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// AuditoriaRiscoDetectionsV2
    /// </summary>
    [DataContract(Name = "AuditoriaRiscoDetectionsV2")]
    public partial class AuditoriaRiscoDetectionsV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditoriaRiscoDetectionsV2" /> class.
        /// </summary>
        /// <param name="violations">Active violations.</param>
        /// <param name="positives">Active positives.</param>
        /// <param name="clientRiskAlerts">Client risk alerts.</param>
        /// <param name="clientBehaviorAlerts">Client behavior alerts.</param>
        /// <param name="clientNegatives">Client negatives.</param>
        public AuditoriaRiscoDetectionsV2(List<AuditoriaRiscoDetectionItemV2> violations = default, List<AuditoriaRiscoDetectionItemV2> positives = default, List<Dictionary<string, Object>> clientRiskAlerts = default, List<Dictionary<string, Object>> clientBehaviorAlerts = default, List<AuditoriaRiscoDetectionItemV2> clientNegatives = default)
        {
            this.Violations = violations;
            this.Positives = positives;
            this.ClientRiskAlerts = clientRiskAlerts;
            this.ClientBehaviorAlerts = clientBehaviorAlerts;
            this.ClientNegatives = clientNegatives;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Active violations
        /// </summary>
        /// <value>Active violations</value>
        [DataMember(Name = "violations", EmitDefaultValue = false)]
        public List<AuditoriaRiscoDetectionItemV2> Violations { get; set; }

        /// <summary>
        /// Active positives
        /// </summary>
        /// <value>Active positives</value>
        [DataMember(Name = "positives", EmitDefaultValue = false)]
        public List<AuditoriaRiscoDetectionItemV2> Positives { get; set; }

        /// <summary>
        /// Client risk alerts
        /// </summary>
        /// <value>Client risk alerts</value>
        [DataMember(Name = "client_risk_alerts", EmitDefaultValue = false)]
        public List<Dictionary<string, Object>> ClientRiskAlerts { get; set; }

        /// <summary>
        /// Client behavior alerts
        /// </summary>
        /// <value>Client behavior alerts</value>
        [DataMember(Name = "client_behavior_alerts", EmitDefaultValue = false)]
        public List<Dictionary<string, Object>> ClientBehaviorAlerts { get; set; }

        /// <summary>
        /// Client negatives
        /// </summary>
        /// <value>Client negatives</value>
        [DataMember(Name = "client_negatives", EmitDefaultValue = false)]
        public List<AuditoriaRiscoDetectionItemV2> ClientNegatives { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuditoriaRiscoDetectionsV2 {\n");
            sb.Append("  Violations: ").Append(Violations).Append("\n");
            sb.Append("  Positives: ").Append(Positives).Append("\n");
            sb.Append("  ClientRiskAlerts: ").Append(ClientRiskAlerts).Append("\n");
            sb.Append("  ClientBehaviorAlerts: ").Append(ClientBehaviorAlerts).Append("\n");
            sb.Append("  ClientNegatives: ").Append(ClientNegatives).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
