/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// DiagnosticParticipant
    /// </summary>
    [DataContract(Name = "DiagnosticParticipant")]
    public partial class DiagnosticParticipant : IValidatableObject
    {
        /// <summary>
        /// agent | client | bot
        /// </summary>
        /// <value>agent | client | bot</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RoleEnum
        {
            /// <summary>
            /// Enum Agent for value: agent
            /// </summary>
            [EnumMember(Value = "agent")]
            Agent = 1,

            /// <summary>
            /// Enum Client for value: client
            /// </summary>
            [EnumMember(Value = "client")]
            Client = 2,

            /// <summary>
            /// Enum Bot for value: bot
            /// </summary>
            [EnumMember(Value = "bot")]
            Bot = 3
        }


        /// <summary>
        /// agent | client | bot
        /// </summary>
        /// <value>agent | client | bot</value>
        [DataMember(Name = "role", IsRequired = true, EmitDefaultValue = true)]
        public RoleEnum Role { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DiagnosticParticipant" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DiagnosticParticipant() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DiagnosticParticipant" /> class.
        /// </summary>
        /// <param name="interlocutor">Exact speaker label from the dialog (e.g. &#39;Speaker 1&#39;) (required).</param>
        /// <param name="name">Participant name (optional).</param>
        /// <param name="role">agent | client | bot (required).</param>
        public DiagnosticParticipant(string interlocutor = default, string name = default, RoleEnum role = default)
        {
            // to ensure "interlocutor" is required (not null)
            if (interlocutor == null)
            {
                throw new ArgumentNullException("interlocutor is a required property for DiagnosticParticipant and cannot be null");
            }
            this.Interlocutor = interlocutor;
            this.Role = role;
            this.Name = name;
        }

        /// <summary>
        /// Exact speaker label from the dialog (e.g. &#39;Speaker 1&#39;)
        /// </summary>
        /// <value>Exact speaker label from the dialog (e.g. &#39;Speaker 1&#39;)</value>
        [DataMember(Name = "interlocutor", IsRequired = true, EmitDefaultValue = true)]
        public string Interlocutor { get; set; }

        /// <summary>
        /// Participant name (optional)
        /// </summary>
        /// <value>Participant name (optional)</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DiagnosticParticipant {\n");
            sb.Append("  Interlocutor: ").Append(Interlocutor).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
