/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.47
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// DiagnosticResponse
    /// </summary>
    [DataContract(Name = "DiagnosticResponse")]
    public partial class DiagnosticResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DiagnosticResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DiagnosticResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DiagnosticResponse" /> class.
        /// </summary>
        /// <param name="id">Unique analysis identifier. Prefix &#39;di-&#39; + UUID (required).</param>
        /// <param name="responseLanguage">Language used in the response. E.g.: &#39;pt-BR&#39;, &#39;en-US&#39;, &#39;es-ES&#39; (required).</param>
        /// <param name="varObject">Object type. Always &#39;analysis&#39; (required).</param>
        /// <param name="analysis">The 6 conversation analyses (5 + participants) (required).</param>
        /// <param name="usage">Usage and processing information (required).</param>
        /// <param name="clientReferenceId">Client-supplied ID echoed verbatim (if provided in request).</param>
        public DiagnosticResponse(string id = default, string responseLanguage = default, string varObject = default, DiagnosticAnalysisMap analysis = default, DiagnosticUsage usage = default, string clientReferenceId = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for DiagnosticResponse and cannot be null");
            }
            this.Id = id;
            // to ensure "responseLanguage" is required (not null)
            if (responseLanguage == null)
            {
                throw new ArgumentNullException("responseLanguage is a required property for DiagnosticResponse and cannot be null");
            }
            this.ResponseLanguage = responseLanguage;
            // to ensure "varObject" is required (not null)
            if (varObject == null)
            {
                throw new ArgumentNullException("varObject is a required property for DiagnosticResponse and cannot be null");
            }
            this.Object = varObject;
            // to ensure "analysis" is required (not null)
            if (analysis == null)
            {
                throw new ArgumentNullException("analysis is a required property for DiagnosticResponse and cannot be null");
            }
            this.Analysis = analysis;
            // to ensure "usage" is required (not null)
            if (usage == null)
            {
                throw new ArgumentNullException("usage is a required property for DiagnosticResponse and cannot be null");
            }
            this.Usage = usage;
            this.ClientReferenceId = clientReferenceId;
        }

        /// <summary>
        /// Unique analysis identifier. Prefix &#39;di-&#39; + UUID
        /// </summary>
        /// <value>Unique analysis identifier. Prefix &#39;di-&#39; + UUID</value>
        /*
        <example>di-550e8400-e29b-41d4-a716-446655440000</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Language used in the response. E.g.: &#39;pt-BR&#39;, &#39;en-US&#39;, &#39;es-ES&#39;
        /// </summary>
        /// <value>Language used in the response. E.g.: &#39;pt-BR&#39;, &#39;en-US&#39;, &#39;es-ES&#39;</value>
        /*
        <example>pt-BR</example>
        */
        [DataMember(Name = "response_language", IsRequired = true, EmitDefaultValue = true)]
        public string ResponseLanguage { get; set; }

        /// <summary>
        /// Object type. Always &#39;analysis&#39;
        /// </summary>
        /// <value>Object type. Always &#39;analysis&#39;</value>
        /*
        <example>analysis</example>
        */
        [DataMember(Name = "object", IsRequired = true, EmitDefaultValue = true)]
        public string Object { get; set; }

        /// <summary>
        /// The 6 conversation analyses (5 + participants)
        /// </summary>
        /// <value>The 6 conversation analyses (5 + participants)</value>
        [DataMember(Name = "analysis", IsRequired = true, EmitDefaultValue = true)]
        public DiagnosticAnalysisMap Analysis { get; set; }

        /// <summary>
        /// Usage and processing information
        /// </summary>
        /// <value>Usage and processing information</value>
        [DataMember(Name = "usage", IsRequired = true, EmitDefaultValue = true)]
        public DiagnosticUsage Usage { get; set; }

        /// <summary>
        /// Client-supplied ID echoed verbatim (if provided in request)
        /// </summary>
        /// <value>Client-supplied ID echoed verbatim (if provided in request)</value>
        /*
        <example>call-2026-08-30-001</example>
        */
        [DataMember(Name = "client_reference_id", EmitDefaultValue = true)]
        public string ClientReferenceId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DiagnosticResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ResponseLanguage: ").Append(ResponseLanguage).Append("\n");
            sb.Append("  Object: ").Append(Object).Append("\n");
            sb.Append("  Analysis: ").Append(Analysis).Append("\n");
            sb.Append("  Usage: ").Append(Usage).Append("\n");
            sb.Append("  ClientReferenceId: ").Append(ClientReferenceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
