/*
 * FalaAI API
 *
 * Transcribe, diagnose and score calls with 3 simple endpoints.  **Endpoints:** - `POST /v1/audio/transcriptions` — Audio to text - `POST /v1/analyze/diagnostic` — Conversation analysis - `POST /v1/analyze/auditoriaRisco` — Compliance audit  **Complete flow (Python):** ```python import httpx  API = 'https://api01-falaai.action.tec.br' KEY = 'fai_xxx' HD = {'Authorization': f'Bearer {KEY}'}  # 1. Transcribe files = {'file': open('call.mp3', 'rb')} resp = httpx.post(f'{API}/v1/audio/transcriptions', headers=HD, files=files, data={'model': 'falaai-transcribe-1', 'language': 'pt'}) tr = resp.json() print(f'Text: {tr[\"text\"][:100]}...')  # 2. Diagnose resp = httpx.post(f'{API}/v1/analyze/diagnostic', headers=HD, json={'dialog': tr['dialog'], 'language': 'pt-BR', 'duration_seconds': tr['duration_seconds']}) diag = resp.json() print(f'Sentiment: {diag[\"analysis\"][\"sentiment\"][\"list_choice\"]}') print(f'Summary: {diag[\"analysis\"][\"dialogue_summary\"][\"explanation\"][:100]}...')  # 3. Audit resp = httpx.post(f'{API}/v1/analyze/auditoriaRisco', headers=HD, json={'dialogo': tr['dialog'], 'duration_seconds': tr['duration_seconds']}) audit = resp.json() print(f'Score: {audit[\"audit_score\"]} | Verdict: {audit[\"verdict\"]}') print(f'Detections: {audit[\"total_detections\"]} | Violations: {len(audit[\"violations\"])} | Positives: {len(audit[\"positives\"])}') ```  **Authentication:** All endpoints require an API Key in the `Authorization` header: `Bearer fai_xxx`  Get your API Key at [falaai.action.tec.br/api](https://falaai.action.tec.br/api)
 *
 * The version of the OpenAPI document: 1.21.48
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// HealthResponse
    /// </summary>
    [DataContract(Name = "HealthResponse")]
    public partial class HealthResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HealthResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HealthResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HealthResponse" /> class.
        /// </summary>
        /// <param name="status">Overall API status (required).</param>
        /// <param name="varVersion">Current API version (required).</param>
        /// <param name="uptimeSeconds">Uptime in seconds (required).</param>
        /// <param name="database">Database connection status (required).</param>
        /// <param name="phase">Development phase (required).</param>
        /// <param name="launchDate">Expected public launch date (required).</param>
        public HealthResponse(string status = default, string varVersion = default, int uptimeSeconds = default, bool database = default, string phase = default, string launchDate = default)
        {
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for HealthResponse and cannot be null");
            }
            this.Status = status;
            // to ensure "varVersion" is required (not null)
            if (varVersion == null)
            {
                throw new ArgumentNullException("varVersion is a required property for HealthResponse and cannot be null");
            }
            this.VarVersion = varVersion;
            this.UptimeSeconds = uptimeSeconds;
            this.Database = database;
            // to ensure "phase" is required (not null)
            if (phase == null)
            {
                throw new ArgumentNullException("phase is a required property for HealthResponse and cannot be null");
            }
            this.Phase = phase;
            // to ensure "launchDate" is required (not null)
            if (launchDate == null)
            {
                throw new ArgumentNullException("launchDate is a required property for HealthResponse and cannot be null");
            }
            this.LaunchDate = launchDate;
        }

        /// <summary>
        /// Overall API status
        /// </summary>
        /// <value>Overall API status</value>
        /*
        <example>ok</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Current API version
        /// </summary>
        /// <value>Current API version</value>
        /*
        <example>api_v1.5.2</example>
        */
        [DataMember(Name = "version", IsRequired = true, EmitDefaultValue = true)]
        public string VarVersion { get; set; }

        /// <summary>
        /// Uptime in seconds
        /// </summary>
        /// <value>Uptime in seconds</value>
        /*
        <example>3600</example>
        */
        [DataMember(Name = "uptime_seconds", IsRequired = true, EmitDefaultValue = true)]
        public int UptimeSeconds { get; set; }

        /// <summary>
        /// Database connection status
        /// </summary>
        /// <value>Database connection status</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "database", IsRequired = true, EmitDefaultValue = true)]
        public bool Database { get; set; }

        /// <summary>
        /// Development phase
        /// </summary>
        /// <value>Development phase</value>
        /*
        <example>development</example>
        */
        [DataMember(Name = "phase", IsRequired = true, EmitDefaultValue = true)]
        public string Phase { get; set; }

        /// <summary>
        /// Expected public launch date
        /// </summary>
        /// <value>Expected public launch date</value>
        /*
        <example>2026-08-01</example>
        */
        [DataMember(Name = "launch_date", IsRequired = true, EmitDefaultValue = true)]
        public string LaunchDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HealthResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  UptimeSeconds: ").Append(UptimeSeconds).Append("\n");
            sb.Append("  Database: ").Append(Database).Append("\n");
            sb.Append("  Phase: ").Append(Phase).Append("\n");
            sb.Append("  LaunchDate: ").Append(LaunchDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
