/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// RiskAuditParticipantsV2
    /// </summary>
    [DataContract(Name = "RiskAuditParticipantsV2")]
    public partial class RiskAuditParticipantsV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RiskAuditParticipantsV2" /> class.
        /// </summary>
        /// <param name="identified">Identified participants.</param>
        /// <param name="callDirection">inbound/outbound.</param>
        /// <param name="roleInferenceReliable">Role inference reliability (default to true).</param>
        /// <param name="identificationStatus">Identification status (default to &quot;none&quot;).</param>
        /// <param name="unidentifiedItemsCount">Unidentified items count (default to 0).</param>
        public RiskAuditParticipantsV2(List<RiskAuditParticipantV2> identified = default, string callDirection = default, bool roleInferenceReliable = true, string identificationStatus = @"none", int unidentifiedItemsCount = 0)
        {
            this.Identified = identified;
            this.CallDirection = callDirection;
            this.RoleInferenceReliable = roleInferenceReliable;
            // use default value if no "identificationStatus" provided
            this.IdentificationStatus = identificationStatus ?? @"none";
            this.UnidentifiedItemsCount = unidentifiedItemsCount;
        }

        /// <summary>
        /// Identified participants
        /// </summary>
        /// <value>Identified participants</value>
        [DataMember(Name = "identified", EmitDefaultValue = false)]
        public List<RiskAuditParticipantV2> Identified { get; set; }

        /// <summary>
        /// inbound/outbound
        /// </summary>
        /// <value>inbound/outbound</value>
        [DataMember(Name = "call_direction", EmitDefaultValue = true)]
        public string CallDirection { get; set; }

        /// <summary>
        /// Role inference reliability
        /// </summary>
        /// <value>Role inference reliability</value>
        [DataMember(Name = "role_inference_reliable", EmitDefaultValue = true)]
        public bool RoleInferenceReliable { get; set; }

        /// <summary>
        /// Identification status
        /// </summary>
        /// <value>Identification status</value>
        [DataMember(Name = "identification_status", EmitDefaultValue = false)]
        public string IdentificationStatus { get; set; }

        /// <summary>
        /// Unidentified items count
        /// </summary>
        /// <value>Unidentified items count</value>
        [DataMember(Name = "unidentified_items_count", EmitDefaultValue = false)]
        public int UnidentifiedItemsCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RiskAuditParticipantsV2 {\n");
            sb.Append("  Identified: ").Append(Identified).Append("\n");
            sb.Append("  CallDirection: ").Append(CallDirection).Append("\n");
            sb.Append("  RoleInferenceReliable: ").Append(RoleInferenceReliable).Append("\n");
            sb.Append("  IdentificationStatus: ").Append(IdentificationStatus).Append("\n");
            sb.Append("  UnidentifiedItemsCount: ").Append(UnidentifiedItemsCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
