/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// RiskAuditRequest
    /// </summary>
    [DataContract(Name = "RiskAuditRequest")]
    public partial class RiskAuditRequest : IValidatableObject
    {
        /// <summary>
        /// Who originated the call. inbound&#x3D;client called, outbound&#x3D;company called. If omitted, LLM infers from context.
        /// </summary>
        /// <value>Who originated the call. inbound&#x3D;client called, outbound&#x3D;company called. If omitted, LLM infers from context.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CallDirectionEnum
        {
            /// <summary>
            /// Enum Inbound for value: inbound
            /// </summary>
            [EnumMember(Value = "inbound")]
            Inbound = 1,

            /// <summary>
            /// Enum Outbound for value: outbound
            /// </summary>
            [EnumMember(Value = "outbound")]
            Outbound = 2
        }


        /// <summary>
        /// Who originated the call. inbound&#x3D;client called, outbound&#x3D;company called. If omitted, LLM infers from context.
        /// </summary>
        /// <value>Who originated the call. inbound&#x3D;client called, outbound&#x3D;company called. If omitted, LLM infers from context.</value>
        [DataMember(Name = "call_direction", EmitDefaultValue = true)]
        public CallDirectionEnum? CallDirection { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RiskAuditRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RiskAuditRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RiskAuditRequest" /> class.
        /// </summary>
        /// <param name="model">Analysis model. Always &#39;falaai-risk-audit-1&#39; (default to &quot;falaai-risk-audit-1&quot;).</param>
        /// <param name="text">Plain transcript (fallback if dialog is empty). At least one of &#39;dialog&#39; or &#39;text&#39; required. Max 300,000 characters (default to &quot;&quot;).</param>
        /// <param name="dialog">Diarized transcript with speaker turns. PRIMARY source. Speaker labels accepted (any case): &#39;Speaker N&#39;, &#39;Interlocutor N&#39;, &#39;Hablante N&#39;, &#39;Locutor N&#39;, &#39;Orador N&#39; (space or underscore). Normalized internally to &#39;Speaker N&#39; in the response. Max 300,000 characters (default to &quot;&quot;).</param>
        /// <param name="audioEvents">Audio events with timestamps (correlated with turns when diarization is present).</param>
        /// <param name="durationSeconds">Total audio duration in seconds. Required. Max 3h (10800s). (required).</param>
        /// <param name="language">Language of the transcript being analyzed. Must match the dialog/text language. Accepted: pt-BR, en-US, es-ES. (required).</param>
        /// <param name="responseLanguage">Language for analysis results (labels, categories, levels, actions, HTML report). Can differ from &#39;language&#39;. Accepted: pt-BR, en-US, es-ES. (required).</param>
        /// <param name="callDirection">Who originated the call. inbound&#x3D;client called, outbound&#x3D;company called. If omitted, LLM infers from context..</param>
        /// <param name="participants">Explicit participant roles. If omitted, LLM infers from dialog (Lei 17). When provided, used as ground truth — no inference..</param>
        /// <param name="responseFormat">Response format version. v1&#x3D;legacy flat PT-BR, v2&#x3D;structured EN-US blocks. (default to &quot;v2&quot;).</param>
        /// <param name="clientReferenceId">Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency..</param>
        public RiskAuditRequest(string model = @"falaai-risk-audit-1", string text = @"", string dialog = @"", List<DiagnosticAudioEvent> audioEvents = default, decimal durationSeconds = default, string language = default, string responseLanguage = default, CallDirectionEnum? callDirection = default, List<Participant> participants = default, string responseFormat = @"v2", string clientReferenceId = default)
        {
            this.DurationSeconds = durationSeconds;
            // to ensure "language" is required (not null)
            if (language == null)
            {
                throw new ArgumentNullException("language is a required property for RiskAuditRequest and cannot be null");
            }
            this.Language = language;
            // to ensure "responseLanguage" is required (not null)
            if (responseLanguage == null)
            {
                throw new ArgumentNullException("responseLanguage is a required property for RiskAuditRequest and cannot be null");
            }
            this.ResponseLanguage = responseLanguage;
            // use default value if no "model" provided
            this.Model = model ?? @"falaai-risk-audit-1";
            // use default value if no "text" provided
            this.Text = text ?? @"";
            // use default value if no "dialog" provided
            this.Dialog = dialog ?? @"";
            this.AudioEvents = audioEvents;
            this.CallDirection = callDirection;
            this.Participants = participants;
            // use default value if no "responseFormat" provided
            this.ResponseFormat = responseFormat ?? @"v2";
            this.ClientReferenceId = clientReferenceId;
        }

        /// <summary>
        /// Analysis model. Always &#39;falaai-risk-audit-1&#39;
        /// </summary>
        /// <value>Analysis model. Always &#39;falaai-risk-audit-1&#39;</value>
        [DataMember(Name = "model", EmitDefaultValue = false)]
        public string Model { get; set; }

        /// <summary>
        /// Plain transcript (fallback if dialog is empty). At least one of &#39;dialog&#39; or &#39;text&#39; required. Max 300,000 characters
        /// </summary>
        /// <value>Plain transcript (fallback if dialog is empty). At least one of &#39;dialog&#39; or &#39;text&#39; required. Max 300,000 characters</value>
        [DataMember(Name = "text", EmitDefaultValue = false)]
        public string Text { get; set; }

        /// <summary>
        /// Diarized transcript with speaker turns. PRIMARY source. Speaker labels accepted (any case): &#39;Speaker N&#39;, &#39;Interlocutor N&#39;, &#39;Hablante N&#39;, &#39;Locutor N&#39;, &#39;Orador N&#39; (space or underscore). Normalized internally to &#39;Speaker N&#39; in the response. Max 300,000 characters
        /// </summary>
        /// <value>Diarized transcript with speaker turns. PRIMARY source. Speaker labels accepted (any case): &#39;Speaker N&#39;, &#39;Interlocutor N&#39;, &#39;Hablante N&#39;, &#39;Locutor N&#39;, &#39;Orador N&#39; (space or underscore). Normalized internally to &#39;Speaker N&#39; in the response. Max 300,000 characters</value>
        [DataMember(Name = "dialog", EmitDefaultValue = false)]
        public string Dialog { get; set; }

        /// <summary>
        /// Audio events with timestamps (correlated with turns when diarization is present)
        /// </summary>
        /// <value>Audio events with timestamps (correlated with turns when diarization is present)</value>
        [DataMember(Name = "audio_events", EmitDefaultValue = false)]
        public List<DiagnosticAudioEvent> AudioEvents { get; set; }

        /// <summary>
        /// Total audio duration in seconds. Required. Max 3h (10800s).
        /// </summary>
        /// <value>Total audio duration in seconds. Required. Max 3h (10800s).</value>
        [DataMember(Name = "duration_seconds", IsRequired = true, EmitDefaultValue = true)]
        public decimal DurationSeconds { get; set; }

        /// <summary>
        /// Language of the transcript being analyzed. Must match the dialog/text language. Accepted: pt-BR, en-US, es-ES.
        /// </summary>
        /// <value>Language of the transcript being analyzed. Must match the dialog/text language. Accepted: pt-BR, en-US, es-ES.</value>
        [DataMember(Name = "language", IsRequired = true, EmitDefaultValue = true)]
        public string Language { get; set; }

        /// <summary>
        /// Language for analysis results (labels, categories, levels, actions, HTML report). Can differ from &#39;language&#39;. Accepted: pt-BR, en-US, es-ES.
        /// </summary>
        /// <value>Language for analysis results (labels, categories, levels, actions, HTML report). Can differ from &#39;language&#39;. Accepted: pt-BR, en-US, es-ES.</value>
        [DataMember(Name = "response_language", IsRequired = true, EmitDefaultValue = true)]
        public string ResponseLanguage { get; set; }

        /// <summary>
        /// Explicit participant roles. If omitted, LLM infers from dialog (Lei 17). When provided, used as ground truth — no inference.
        /// </summary>
        /// <value>Explicit participant roles. If omitted, LLM infers from dialog (Lei 17). When provided, used as ground truth — no inference.</value>
        [DataMember(Name = "participants", EmitDefaultValue = true)]
        public List<Participant> Participants { get; set; }

        /// <summary>
        /// Response format version. v1&#x3D;legacy flat PT-BR, v2&#x3D;structured EN-US blocks.
        /// </summary>
        /// <value>Response format version. v1&#x3D;legacy flat PT-BR, v2&#x3D;structured EN-US blocks.</value>
        [DataMember(Name = "response_format", EmitDefaultValue = false)]
        public string ResponseFormat { get; set; }

        /// <summary>
        /// Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency.
        /// </summary>
        /// <value>Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency.</value>
        [DataMember(Name = "client_reference_id", EmitDefaultValue = true)]
        public string ClientReferenceId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RiskAuditRequest {\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Dialog: ").Append(Dialog).Append("\n");
            sb.Append("  AudioEvents: ").Append(AudioEvents).Append("\n");
            sb.Append("  DurationSeconds: ").Append(DurationSeconds).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  ResponseLanguage: ").Append(ResponseLanguage).Append("\n");
            sb.Append("  CallDirection: ").Append(CallDirection).Append("\n");
            sb.Append("  Participants: ").Append(Participants).Append("\n");
            sb.Append("  ResponseFormat: ").Append(ResponseFormat).Append("\n");
            sb.Append("  ClientReferenceId: ").Append(ClientReferenceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Text (string) maxLength
            if (this.Text != null && this.Text.Length > 300000)
            {
                yield return new ValidationResult("Invalid value for Text, length must be less than 300000.", new [] { "Text" });
            }

            // Dialog (string) maxLength
            if (this.Dialog != null && this.Dialog.Length > 300000)
            {
                yield return new ValidationResult("Invalid value for Dialog, length must be less than 300000.", new [] { "Dialog" });
            }

            // DurationSeconds (decimal) minimum
            if (this.DurationSeconds < (decimal)1.0)
            {
                yield return new ValidationResult("Invalid value for DurationSeconds, must be a value greater than or equal to 1.0.", new [] { "DurationSeconds" });
            }

            if (this.ResponseFormat != null) {
                // ResponseFormat (string) pattern
                Regex regexResponseFormat = new Regex(@"^v[0-9]+$", RegexOptions.CultureInvariant);
                if (!regexResponseFormat.Match(this.ResponseFormat).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ResponseFormat, must match a pattern of " + regexResponseFormat, new [] { "ResponseFormat" });
                }
            }

            yield break;
        }
    }

}
