/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// RiskAuditUsageV2
    /// </summary>
    [DataContract(Name = "RiskAuditUsageV2")]
    public partial class RiskAuditUsageV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RiskAuditUsageV2" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RiskAuditUsageV2() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RiskAuditUsageV2" /> class.
        /// </summary>
        /// <param name="characters">Characters analyzed (required).</param>
        /// <param name="creditsConsumed">Credits consumed (required).</param>
        /// <param name="processingMs">Processing time (ms) (required).</param>
        public RiskAuditUsageV2(int characters = default, int creditsConsumed = default, int processingMs = default)
        {
            this.Characters = characters;
            this.CreditsConsumed = creditsConsumed;
            this.ProcessingMs = processingMs;
        }

        /// <summary>
        /// Characters analyzed
        /// </summary>
        /// <value>Characters analyzed</value>
        [DataMember(Name = "characters", IsRequired = true, EmitDefaultValue = true)]
        public int Characters { get; set; }

        /// <summary>
        /// Credits consumed
        /// </summary>
        /// <value>Credits consumed</value>
        [DataMember(Name = "credits_consumed", IsRequired = true, EmitDefaultValue = true)]
        public int CreditsConsumed { get; set; }

        /// <summary>
        /// Processing time (ms)
        /// </summary>
        /// <value>Processing time (ms)</value>
        [DataMember(Name = "processing_ms", IsRequired = true, EmitDefaultValue = true)]
        public int ProcessingMs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RiskAuditUsageV2 {\n");
            sb.Append("  Characters: ").Append(Characters).Append("\n");
            sb.Append("  CreditsConsumed: ").Append(CreditsConsumed).Append("\n");
            sb.Append("  ProcessingMs: ").Append(ProcessingMs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
