/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// RiskAuditAuditDecisionsV2
    /// </summary>
    [DataContract(Name = "RiskAuditAuditDecisionsV2")]
    public partial class RiskAuditAuditDecisionsV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RiskAuditAuditDecisionsV2" /> class.
        /// </summary>
        /// <param name="riskOrigin">Risk origin.</param>
        /// <param name="hasZeroToleranceViolation">Has zero-tolerance violation.</param>
        /// <param name="deterministicValidatorChanges">Deterministic validator changes.</param>
        public RiskAuditAuditDecisionsV2(string riskOrigin = default, bool? hasZeroToleranceViolation = default, List<Object> deterministicValidatorChanges = default)
        {
            this.RiskOrigin = riskOrigin;
            this.HasZeroToleranceViolation = hasZeroToleranceViolation;
            this.DeterministicValidatorChanges = deterministicValidatorChanges;
        }

        /// <summary>
        /// Risk origin
        /// </summary>
        /// <value>Risk origin</value>
        [DataMember(Name = "risk_origin", EmitDefaultValue = true)]
        public string RiskOrigin { get; set; }

        /// <summary>
        /// Has zero-tolerance violation
        /// </summary>
        /// <value>Has zero-tolerance violation</value>
        [DataMember(Name = "has_zero_tolerance_violation", EmitDefaultValue = true)]
        public bool? HasZeroToleranceViolation { get; set; }

        /// <summary>
        /// Deterministic validator changes
        /// </summary>
        /// <value>Deterministic validator changes</value>
        [DataMember(Name = "deterministic_validator_changes", EmitDefaultValue = false)]
        public List<Object> DeterministicValidatorChanges { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RiskAuditAuditDecisionsV2 {\n");
            sb.Append("  RiskOrigin: ").Append(RiskOrigin).Append("\n");
            sb.Append("  HasZeroToleranceViolation: ").Append(HasZeroToleranceViolation).Append("\n");
            sb.Append("  DeterministicValidatorChanges: ").Append(DeterministicValidatorChanges).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
