/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// RiskAuditV2Response
    /// </summary>
    [DataContract(Name = "RiskAuditV2Response")]
    public partial class RiskAuditV2Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RiskAuditV2Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RiskAuditV2Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RiskAuditV2Response" /> class.
        /// </summary>
        /// <param name="response">Public response V2 — always returned (required).</param>
        public RiskAuditV2Response(RiskAuditV2 response = default)
        {
            // to ensure "response" is required (not null)
            if (response == null)
            {
                throw new ArgumentNullException("response is a required property for RiskAuditV2Response and cannot be null");
            }
            this.Response = response;
        }

        /// <summary>
        /// Public response V2 — always returned
        /// </summary>
        /// <value>Public response V2 — always returned</value>
        [DataMember(Name = "response", IsRequired = true, EmitDefaultValue = true)]
        public RiskAuditV2 Response { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RiskAuditV2Response {\n");
            sb.Append("  Response: ").Append(Response).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
