/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.51
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// TranscriptionUsage
    /// </summary>
    [DataContract(Name = "TranscriptionUsage")]
    public partial class TranscriptionUsage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TranscriptionUsage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TranscriptionUsage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TranscriptionUsage" /> class.
        /// </summary>
        /// <param name="audioSeconds">Actual audio duration processed in seconds (required).</param>
        /// <param name="creditsConsumed">Number of credits consumed in this request (required).</param>
        /// <param name="processingMs">Total processing time in milliseconds (required).</param>
        public TranscriptionUsage(decimal audioSeconds = default, int creditsConsumed = default, int processingMs = default)
        {
            this.AudioSeconds = audioSeconds;
            this.CreditsConsumed = creditsConsumed;
            this.ProcessingMs = processingMs;
        }

        /// <summary>
        /// Actual audio duration processed in seconds
        /// </summary>
        /// <value>Actual audio duration processed in seconds</value>
        [DataMember(Name = "audio_seconds", IsRequired = true, EmitDefaultValue = true)]
        public decimal AudioSeconds { get; set; }

        /// <summary>
        /// Number of credits consumed in this request
        /// </summary>
        /// <value>Number of credits consumed in this request</value>
        [DataMember(Name = "credits_consumed", IsRequired = true, EmitDefaultValue = true)]
        public int CreditsConsumed { get; set; }

        /// <summary>
        /// Total processing time in milliseconds
        /// </summary>
        /// <value>Total processing time in milliseconds</value>
        [DataMember(Name = "processing_ms", IsRequired = true, EmitDefaultValue = true)]
        public int ProcessingMs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TranscriptionUsage {\n");
            sb.Append("  AudioSeconds: ").Append(AudioSeconds).Append("\n");
            sb.Append("  CreditsConsumed: ").Append(CreditsConsumed).Append("\n");
            sb.Append("  ProcessingMs: ").Append(ProcessingMs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
