/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// UsageLogItem
    /// </summary>
    [DataContract(Name = "UsageLogItem")]
    public partial class UsageLogItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UsageLogItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UsageLogItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UsageLogItem" /> class.
        /// </summary>
        /// <param name="id">Usage log entry id (required).</param>
        /// <param name="endpoint">Endpoint called (required).</param>
        /// <param name="creditsCost">Credits consumed (required).</param>
        /// <param name="status">Result status (required).</param>
        /// <param name="errorsCount">Errors count (required).</param>
        /// <param name="createdAt">ISO 8601 timestamp (required).</param>
        public UsageLogItem(string id = default, string endpoint = default, int creditsCost = default, string status = default, int errorsCount = default, string createdAt = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for UsageLogItem and cannot be null");
            }
            this.Id = id;
            // to ensure "endpoint" is required (not null)
            if (endpoint == null)
            {
                throw new ArgumentNullException("endpoint is a required property for UsageLogItem and cannot be null");
            }
            this.Endpoint = endpoint;
            this.CreditsCost = creditsCost;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for UsageLogItem and cannot be null");
            }
            this.Status = status;
            this.ErrorsCount = errorsCount;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for UsageLogItem and cannot be null");
            }
            this.CreatedAt = createdAt;
        }

        /// <summary>
        /// Usage log entry id
        /// </summary>
        /// <value>Usage log entry id</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Endpoint called
        /// </summary>
        /// <value>Endpoint called</value>
        [DataMember(Name = "endpoint", IsRequired = true, EmitDefaultValue = true)]
        public string Endpoint { get; set; }

        /// <summary>
        /// Credits consumed
        /// </summary>
        /// <value>Credits consumed</value>
        [DataMember(Name = "credits_cost", IsRequired = true, EmitDefaultValue = true)]
        public int CreditsCost { get; set; }

        /// <summary>
        /// Result status
        /// </summary>
        /// <value>Result status</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Errors count
        /// </summary>
        /// <value>Errors count</value>
        [DataMember(Name = "errors_count", IsRequired = true, EmitDefaultValue = true)]
        public int ErrorsCount { get; set; }

        /// <summary>
        /// ISO 8601 timestamp
        /// </summary>
        /// <value>ISO 8601 timestamp</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UsageLogItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Endpoint: ").Append(Endpoint).Append("\n");
            sb.Append("  CreditsCost: ").Append(CreditsCost).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ErrorsCount: ").Append(ErrorsCount).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
