/*
 * FalaAI API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.21.49
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = FalaAI.Api.Client.FileParameter;
using OpenAPIDateConverter = FalaAI.Api.Client.OpenAPIDateConverter;

namespace FalaAI.Api.Model
{
    /// <summary>
    /// UsageByKeyItem
    /// </summary>
    [DataContract(Name = "UsageByKeyItem")]
    public partial class UsageByKeyItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UsageByKeyItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UsageByKeyItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UsageByKeyItem" /> class.
        /// </summary>
        /// <param name="keyId">API key id (required).</param>
        /// <param name="keyName">API key name (required).</param>
        /// <param name="totalCredits">Total credits consumed by the key (required).</param>
        /// <param name="requestCount">Number of requests (required).</param>
        /// <param name="lastUsed">ISO 8601 of last use (null if never).</param>
        public UsageByKeyItem(string keyId = default, string keyName = default, int totalCredits = default, int requestCount = default, string lastUsed = default)
        {
            // to ensure "keyId" is required (not null)
            if (keyId == null)
            {
                throw new ArgumentNullException("keyId is a required property for UsageByKeyItem and cannot be null");
            }
            this.KeyId = keyId;
            // to ensure "keyName" is required (not null)
            if (keyName == null)
            {
                throw new ArgumentNullException("keyName is a required property for UsageByKeyItem and cannot be null");
            }
            this.KeyName = keyName;
            this.TotalCredits = totalCredits;
            this.RequestCount = requestCount;
            this.LastUsed = lastUsed;
        }

        /// <summary>
        /// API key id
        /// </summary>
        /// <value>API key id</value>
        [DataMember(Name = "key_id", IsRequired = true, EmitDefaultValue = true)]
        public string KeyId { get; set; }

        /// <summary>
        /// API key name
        /// </summary>
        /// <value>API key name</value>
        [DataMember(Name = "key_name", IsRequired = true, EmitDefaultValue = true)]
        public string KeyName { get; set; }

        /// <summary>
        /// Total credits consumed by the key
        /// </summary>
        /// <value>Total credits consumed by the key</value>
        [DataMember(Name = "total_credits", IsRequired = true, EmitDefaultValue = true)]
        public int TotalCredits { get; set; }

        /// <summary>
        /// Number of requests
        /// </summary>
        /// <value>Number of requests</value>
        [DataMember(Name = "request_count", IsRequired = true, EmitDefaultValue = true)]
        public int RequestCount { get; set; }

        /// <summary>
        /// ISO 8601 of last use (null if never)
        /// </summary>
        /// <value>ISO 8601 of last use (null if never)</value>
        [DataMember(Name = "last_used", EmitDefaultValue = true)]
        public string LastUsed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UsageByKeyItem {\n");
            sb.Append("  KeyId: ").Append(KeyId).Append("\n");
            sb.Append("  KeyName: ").Append(KeyName).Append("\n");
            sb.Append("  TotalCredits: ").Append(TotalCredits).Append("\n");
            sb.Append("  RequestCount: ").Append(RequestCount).Append("\n");
            sb.Append("  LastUsed: ").Append(LastUsed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
